package fit.jvode.bridj.nvector;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : include\nvector\nvector_serial.h:67</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class _N_VectorContent_Serial extends StructObject {
	public _N_VectorContent_Serial() {
		super();
	}
	public _N_VectorContent_Serial(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public int length() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public _N_VectorContent_Serial length(int length) {
		this.io.setIntField(this, 0, length);
		return this;
	}
	@Field(1) 
	public int own_data() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public _N_VectorContent_Serial own_data(int own_data) {
		this.io.setIntField(this, 1, own_data);
		return this;
	}
	/// C type : realtype*
	@Field(2) 
	public Pointer<Double > data() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : realtype*
	@Field(2) 
	public _N_VectorContent_Serial data(Pointer<Double > data) {
		this.io.setPointerField(this, 2, data);
		return this;
	}
}
