package fit.jvode.bridj.nvector;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : include\nvector\nvector_parallel.h:88</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class _N_VectorContent_Parallel extends StructObject {
	public _N_VectorContent_Parallel() {
		super();
	}
	public _N_VectorContent_Parallel(Pointer pointer) {
		super(pointer);
	}
	/// local vector length
	@Field(0) 
	public int local_length() {
		return this.io.getIntField(this, 0);
	}
	/// local vector length
	@Field(0) 
	public _N_VectorContent_Parallel local_length(int local_length) {
		this.io.setIntField(this, 0, local_length);
		return this;
	}
	/// global vector length
	@Field(1) 
	public int global_length() {
		return this.io.getIntField(this, 1);
	}
	/// global vector length
	@Field(1) 
	public _N_VectorContent_Parallel global_length(int global_length) {
		this.io.setIntField(this, 1, global_length);
		return this;
	}
	/// ownership of data
	@Field(2) 
	public int own_data() {
		return this.io.getIntField(this, 2);
	}
	/// ownership of data
	@Field(2) 
	public _N_VectorContent_Parallel own_data(int own_data) {
		this.io.setIntField(this, 2, own_data);
		return this;
	}
	/**
	 * local data array<br>
	 * C type : realtype*
	 */
	@Field(3) 
	public Pointer<Double > data() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * local data array<br>
	 * C type : realtype*
	 */
	@Field(3) 
	public _N_VectorContent_Parallel data(Pointer<Double > data) {
		this.io.setPointerField(this, 3, data);
		return this;
	}
}
