package util;



public class Errors {
	public static final String[] ERRORS =
	{
/*  0 */		"'%s' is not a valid %s filename - has to have an extension '%s'",
/*  1 */		"'%s' is not a valid %s extension - has to be '%s'",
/*  2 */		"the filename '%s' and the %s name '%s' are different - they have to be identical",
/*  3 */		"'%s' is not a valid model filename - has to have an extension '%s'",
/*  4 */		"'%s' is not a valid model extension - has to be '%s'",
/*  5 */		"the filename '%s' and the model name '%s' are different - they have to be identical",
/*  6 */		"'%s' is not a structure",
/*  7 */		"'%s' is an unknown(unsupported) structure",
/*  8 */		"'%s' is not an ID - ID was expected",
/*  9 */		"property '%s' has unknown(unsupported) type '%s'",

/* 10 */		"property '%s' has cardinality from %.0f to %.0f - %d value(s) were specified",
/* 11 */		"property '%s' has value of type '%s' - must be of type '%s'",
/* 12 */		"structure '%s' is missing mandatory property '%s'",
/* 13 */		"reference '%s' does not exist, should be one of %s",
/* 14 */		"'%s' is not a PP - iterators allowed only in PPs",
/* 15 */		"'%s' already has one iterated element, only one is allowed",
/* 16 */		"the iterating element '%s' within the iterator must be an ID",
/* 17 */		"the iterated element '%s' within the iterator must be an ID",
/* 18 */		"the iterated element '%s' within the iterator is not a valid reference to a parameter of the process",
/* 19 */		"the reference '%s' is of type '%s' - only IDs and ITERs are allowed",

/* 20 */		"the structure '%s' in property '%s' redefines the structure '%s' which was defined is some of its ancestors - redefining structures is not allowed",
/* 21 */		"in TP '%s', the PP in position %d references TP '%s' but has invalid number of arguments - has %d, should have %d",
/* 22 */		"in TP '%s', in the PP in position %d that references TP '%s', the argument in possition %d '%s' has unsuitable type '%s' and references parameter '%s' which should be of type '%s' or a subtype",
/* 23 */		"in TP '%s', in the PP in position %d that references TP '%s', the argument in possition %d '%s' has unsuitable cardinality %s and references parameter '%s' which has cardinality %s",
/* 24 */		"circular inheritance in TE hierarcy - '%s' is a subentity of itself",
/* 25 */		"circular inheritance in TP hierarcy - '%s' is a subprocess of itself",
/* 26 */		"instance '%s' doesn't have a template associated",
/* 27 */		"instance '%s', in property '%s' contains instance '%s' which is not defined in the template '%s'",
/* 28 */		"instance '%s', in property '%s' lacks instance '%s' which is defined in the template '%s'",
/* 29 */		"in instance '%s', the property '%s' has the wrong number of values - has %d, should have %d, which is decided by the number of values the template has",

/* 30 */		"in instance '%s', the property '%s' has only %d value(s) which is too few",
/* 31 */		"in instance '%s', the property '%s' has insuficient number of values. In the template, the component process '%s' is iterated for the values of '%s', and for this instance there are %d of them",
/* 32 */		"in instance '%s', the property '%s' has too many values. %d value(s) were expected and %d value(s) were found",
/* 33 */		"%1$s expected - cannot create %1$s from token type '%2$s'",
/* 34 */		"the string '%s' is not properly formated. Either doesn't start or end with \" or has \" inside the string",
/* 35 */		"signed %s expected - only unary PLUS/MINUS can be used, found a PLUS/MINUS with %d arguments",
/* 36 */		"interval excepted - intervals can have 1 or 2 bounds, this one has %d",
/* 37 */		"%s literal expected - found '%s', expected one of %s",
/* 38 */		"%s literal expected - found token of type '%s', expected one of %s",
/* 39 */		"in instance '%s', in property 'arguments', the argument in position %d has cardinality %d, and the parameter '%s' in the template that corresponds to this argument has allowed cardinality %s",

/* 40 */		"in instance '%s', in property 'arguments', in the argment in position %d, the entity '%s' is of type '%s', and the parameter '%s' in the template that corresponds to this argument allows type '%s' or its subtypes",
/* 41 */		"in instance '%s', in property 'processes', the process in position %d '%s' has type '%s' which is inappropriate, should be of type '%s' or its subtypes",
/*#42#*/		"in instance '%s', in property 'processes', in the process in position %d '%s', the argument in position %d has cardinality %d, should be in %s",
/* 43 */		"in instance '%s', in property 'processes', in the process in position %d '%s', the argument in position %d has value: %s, should be: %s",
/* 44 */		"a structure with the name '%s' is already defined",
/* 45 */		"malformed equation : found token of type '%s', expected of type '%s'",
/* 46 */		"malformed equation : found token of type '%s', expected one of types %s",
/* 47 */		"malformed differantial equation : left side should have the form td(<variable>)",
/* 48 */		"malfomred differential equation : '%s' expected, '%s' found",
/* 49 */		"malformed equation : '%s' is not a valid parameter identifier",

/* 50 */		"malformed equation : '%s' is not a valid variable in parameter '%s'",
/* 51 */		"malformed equation : operator '%s' is should have %d arguments, but %d were found",
/* 52 */		"malformed equation : function '%s' does not exist, expected one of %s",
/* 53 */		"malformed equation : token of type '%s' is not valid in the given context",
/* 54 */		"malformed equation : function '%s' has arity %d, but was called with %d arguments",
/* 55 */		"malformed equation : '%s' is not a valid constant identifier",
/* 56 */		"malformed equation : '%s' is neighter a valid variable nor constant in parameter '%s'",
/* 57 */		"malformed equation : only arguments with cardinality 1 can be referenced in equations - '%s' has cardinality %d",
/* 58 */		"malformed template equation : '%s' is not a valid type of reference, expected one of %s",
/* 59 */		"in template entity '%s', '%s' is an identifier for both variable and constant",

/* 60 */		"in instance '%s', in property 'processes', in the process in position %d '%s', the argument in position %d has has cardinality %d, should have 1",
/* 61 */		"a cycle appears among some of these equations : %s",
/* 62 */		"equation involved in a cycle: %s",
/* 63 */		"variable '%s' is influenced by both differential equations - in processes %s; and algebraic equations - in processes %s",
/* 64 */		"variable '%s' is declared as 'endogenous' but there are no equations for this variable in the model",
/* 65 */		"trying to map model variable '%s' to dataset column '%s'. Already mapped to '%s'",
/* 66 */		"trying to map dataset column '%s' to model variable '%s'. Already mapped to '%s'",
/* 67 */		"dataset column '%s' doesn't exist - should be one of %s",
/* 68 */		"tag <library> is mandatory but missing",
/* 69 */		"tag <command> is mandatory but missing",

/* 70 */		"trying to map dimension '%s' to dataset column '%s'. Already mapped to '%s'",
/* 71 */		"trying to map dataset column '%s' to dimension '%s'. Already mapped to '%s'",
/* 72 */		"'%s' does not refer to a valid model. Should be '%s'",
/* 73 */		"'%s' does not refer to a valid compartment. Should be one of %s",
/* 74 */		"within '%s' there are no entities nor processes named '%s'",
/* 75 */		"within entity '%s' there are no variables nor constants named '%s'",
/* 76 */		"within process '%s' there are no constants named '%s'",
/* 77 */		"trying to map output variable '%s' to dataset column '%s'. Already mapped to '%s'",
/* 78 */		"trying to map dataset column '%s' to output variable '%s'. Already mapped to '%s'",
/* 79 */		"variable '%s' is mapped to column '%s', but the column is not present in the data set",

/* 80 */		"exogenous variables '%s' has no mapping",
/* 81 */		"datasets '%s' and '%s should contain same columns in same order.",
	};
}
