package fit.jvode.jna.nvector;
import com.ochafik.lang.jnaerator.runtime.LibraryExtractor;
import com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper;
import com.ochafik.lang.jnaerator.runtime.Mangling;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.DoubleBuffer;
import java.nio.IntBuffer;

import fit.jvode.jna.sundials.*;
/**
 * JNA Wrapper for library <b>nvector</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NvectorLibrary implements Library {
	public static final String JNA_LIBRARY_NAME = LibraryExtractor.getLibraryPath("sundials_nvecserial", true, NvectorLibrary.class);
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(NvectorLibrary.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	static {
		Native.register(NvectorLibrary.JNA_LIBRARY_NAME);
	}
	/**
	 * Original signature : <code>N_Vector N_VNew_Parallel(MPI_Comm, long int, long int)</code><br>
	 * <i>native declaration : include\nvector\nvector_parallel.h:202</i>
	 */
//	@Mangling({"_Z15N_VNew_Parallel8MPI_Commll", "?N_VNew_Parallel@@YAPA17_generic_N_Vector8MPI_CommJJ@Z"}) 
//	public static native _generic_N_Vector N_VNew_Parallel(NvectorLibrary.MPI_Comm comm, int local_length, int global_length);
//	/**
//	 * Original signature : <code>N_Vector N_VNewEmpty_Parallel(MPI_Comm, long int, long int)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:215</i>
//	 */
//	@Mangling({"_Z20N_VNewEmpty_Parallel8MPI_Commll", "?N_VNewEmpty_Parallel@@YAPA17_generic_N_Vector8MPI_CommJJ@Z"}) 
//	public static native _generic_N_Vector N_VNewEmpty_Parallel(NvectorLibrary.MPI_Comm comm, int local_length, int global_length);
//	/**
//	 * Original signature : <code>N_Vector N_VMake_Parallel(MPI_Comm, long int, long int, realtype*)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:228</i><br>
//	 * @deprecated use the safer methods {@link #N_VMake_Parallel(nvector.NvectorLibrary.MPI_Comm, int, int, java.nio.DoubleBuffer)} and {@link #N_VMake_Parallel(nvector.NvectorLibrary.MPI_Comm, int, int, com.sun.jna.ptr.DoubleByReference)} instead
//	 */
//	@Mangling({"_Z16N_VMake_Parallel8MPI_CommllPd", "?N_VMake_Parallel@@YAPA17_generic_N_Vector8MPI_CommJJPAN@Z"}) 
//	@Deprecated 
//	public static native _generic_N_Vector N_VMake_Parallel(NvectorLibrary.MPI_Comm comm, int local_length, int global_length, DoubleByReference v_data);
//	/**
//	 * Original signature : <code>N_Vector N_VMake_Parallel(MPI_Comm, long int, long int, realtype*)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:228</i>
//	 */
//	@Mangling({"_Z16N_VMake_Parallel8MPI_CommllPd", "?N_VMake_Parallel@@YAPA17_generic_N_Vector8MPI_CommJJPAN@Z"}) 
//	public static native _generic_N_Vector N_VMake_Parallel(NvectorLibrary.MPI_Comm comm, int local_length, int global_length, DoubleBuffer v_data);
//	/**
//	 * Original signature : <code>N_Vector* N_VCloneVectorArray_Parallel(int, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:242</i>
//	 */
//	@Mangling({"_Z28N_VCloneVectorArray_ParalleliP17_generic_N_Vector", "?N_VCloneVectorArray_Parallel@@YAPAPA17_generic_N_VectorHPA17_generic_N_Vector@Z"}) 
//	public static native _generic_N_Vector.ByReference[] N_VCloneVectorArray_Parallel(int count, _generic_N_Vector w);
//	/**
//	 * Original signature : <code>N_Vector* N_VCloneVectorArrayEmpty_Parallel(int, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:253</i>
//	 */
//	@Mangling({"_Z33N_VCloneVectorArrayEmpty_ParalleliP17_generic_N_Vector", "?N_VCloneVectorArrayEmpty_Parallel@@YAPAPA17_generic_N_VectorHPA17_generic_N_Vector@Z"}) 
//	public static native _generic_N_Vector.ByReference[] N_VCloneVectorArrayEmpty_Parallel(int count, _generic_N_Vector w);
//	/**
//	 * Original signature : <code>void N_VDestroyVectorArray_Parallel(N_Vector*, int)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:264</i><br>
//	 * @deprecated use the safer method {@link #N_VDestroyVectorArray_Parallel(sundials._generic_N_Vector.ByReference[], int)} instead
//	 */
//	@Mangling({"_Z30N_VDestroyVectorArray_ParallelPP17_generic_N_Vectori", "?N_VDestroyVectorArray_Parallel@@YAXPAPA17_generic_N_VectorH@Z"}) 
//	@Deprecated 
//	public static native void N_VDestroyVectorArray_Parallel(PointerByReference vs, int count);
//	/**
//	 * Original signature : <code>void N_VDestroyVectorArray_Parallel(N_Vector*, int)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:264</i>
//	 */
//	@Mangling({"_Z30N_VDestroyVectorArray_ParallelPP17_generic_N_Vectori", "?N_VDestroyVectorArray_Parallel@@YAXPAPA17_generic_N_VectorH@Z"}) 
//	public static native void N_VDestroyVectorArray_Parallel(_generic_N_Vector.ByReference vs[], int count);
//	/**
//	 * Original signature : <code>void N_VPrint_Parallel(N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:274</i>
//	 */
//	@Mangling({"_Z17N_VPrint_ParallelP17_generic_N_Vector", "?N_VPrint_Parallel@@YAXPA17_generic_N_Vector@Z"}) 
//	public static native void N_VPrint_Parallel(_generic_N_Vector v);
//	/**
//	 * Original signature : <code>N_Vector N_VCloneEmpty_Parallel(N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:282</i>
//	 */
//	@Mangling({"_Z22N_VCloneEmpty_ParallelP17_generic_N_Vector", "?N_VCloneEmpty_Parallel@@YAPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native _generic_N_Vector N_VCloneEmpty_Parallel(_generic_N_Vector w);
//	/**
//	 * Original signature : <code>N_Vector N_VClone_Parallel(N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:283</i>
//	 */
//	@Mangling({"_Z17N_VClone_ParallelP17_generic_N_Vector", "?N_VClone_Parallel@@YAPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native _generic_N_Vector N_VClone_Parallel(_generic_N_Vector w);
//	/**
//	 * Original signature : <code>void N_VDestroy_Parallel(N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:284</i>
//	 */
//	@Mangling({"_Z19N_VDestroy_ParallelP17_generic_N_Vector", "?N_VDestroy_Parallel@@YAXPA17_generic_N_Vector@Z"}) 
//	public static native void N_VDestroy_Parallel(_generic_N_Vector v);
//	/**
//	 * Original signature : <code>void N_VSpace_Parallel(N_Vector, long int*, long int*)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:285</i><br>
//	 * @deprecated use the safer methods {@link #N_VSpace_Parallel(sundials._generic_N_Vector, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #N_VSpace_Parallel(sundials._generic_N_Vector, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
//	 */
//	@Mangling({"_Z17N_VSpace_ParallelP17_generic_N_VectorPlPl", "?N_VSpace_Parallel@@YAXPA17_generic_N_VectorPAJPAJ@Z"}) 
//	@Deprecated 
//	public static native void N_VSpace_Parallel(_generic_N_Vector v, IntByReference lrw, IntByReference liw);
//	/**
//	 * Original signature : <code>void N_VSpace_Parallel(N_Vector, long int*, long int*)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:285</i>
//	 */
//	@Mangling({"_Z17N_VSpace_ParallelP17_generic_N_VectorPlPl", "?N_VSpace_Parallel@@YAXPA17_generic_N_VectorPAJPAJ@Z"}) 
//	public static native void N_VSpace_Parallel(_generic_N_Vector v, IntBuffer lrw, IntBuffer liw);
//	/**
//	 * Original signature : <code>realtype* N_VGetArrayPointer_Parallel(N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:286</i>
//	 */
//	@Mangling({"_Z27N_VGetArrayPointer_ParallelP17_generic_N_Vector", "?N_VGetArrayPointer_Parallel@@YAPANPA17_generic_N_Vector@Z"}) 
//	public static native DoubleByReference N_VGetArrayPointer_Parallel(_generic_N_Vector v);
//	/**
//	 * Original signature : <code>void N_VSetArrayPointer_Parallel(realtype*, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:287</i><br>
//	 * @deprecated use the safer methods {@link #N_VSetArrayPointer_Parallel(java.nio.DoubleBuffer, sundials._generic_N_Vector)} and {@link #N_VSetArrayPointer_Parallel(com.sun.jna.ptr.DoubleByReference, sundials._generic_N_Vector)} instead
//	 */
//	@Mangling({"_Z27N_VSetArrayPointer_ParallelPdP17_generic_N_Vector", "?N_VSetArrayPointer_Parallel@@YAXPANPA17_generic_N_Vector@Z"}) 
//	@Deprecated 
//	public static native void N_VSetArrayPointer_Parallel(DoubleByReference v_data, _generic_N_Vector v);
//	/**
//	 * Original signature : <code>void N_VSetArrayPointer_Parallel(realtype*, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:287</i>
//	 */
//	@Mangling({"_Z27N_VSetArrayPointer_ParallelPdP17_generic_N_Vector", "?N_VSetArrayPointer_Parallel@@YAXPANPA17_generic_N_Vector@Z"}) 
//	public static native void N_VSetArrayPointer_Parallel(DoubleBuffer v_data, _generic_N_Vector v);
//	/**
//	 * Original signature : <code>void N_VLinearSum_Parallel(realtype, N_Vector, realtype, N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:288</i>
//	 */
//	@Mangling({"_Z21N_VLinearSum_ParalleldP17_generic_N_VectordP17_generic_N_VectorP17_generic_N_Vector", "?N_VLinearSum_Parallel@@YAXNPA17_generic_N_VectorNPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native void N_VLinearSum_Parallel(double a, _generic_N_Vector x, double b, _generic_N_Vector y, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>void N_VConst_Parallel(realtype, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:289</i>
//	 */
//	@Mangling({"_Z17N_VConst_ParalleldP17_generic_N_Vector", "?N_VConst_Parallel@@YAXNPA17_generic_N_Vector@Z"}) 
//	public static native void N_VConst_Parallel(double c, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>void N_VProd_Parallel(N_Vector, N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:290</i>
//	 */
//	@Mangling({"_Z16N_VProd_ParallelP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_Vector", "?N_VProd_Parallel@@YAXPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native void N_VProd_Parallel(_generic_N_Vector x, _generic_N_Vector y, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>void N_VDiv_Parallel(N_Vector, N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:291</i>
//	 */
//	@Mangling({"_Z15N_VDiv_ParallelP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_Vector", "?N_VDiv_Parallel@@YAXPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native void N_VDiv_Parallel(_generic_N_Vector x, _generic_N_Vector y, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>void N_VScale_Parallel(realtype, N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:292</i>
//	 */
//	@Mangling({"_Z17N_VScale_ParalleldP17_generic_N_VectorP17_generic_N_Vector", "?N_VScale_Parallel@@YAXNPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native void N_VScale_Parallel(double c, _generic_N_Vector x, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>void N_VAbs_Parallel(N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:293</i>
//	 */
//	@Mangling({"_Z15N_VAbs_ParallelP17_generic_N_VectorP17_generic_N_Vector", "?N_VAbs_Parallel@@YAXPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native void N_VAbs_Parallel(_generic_N_Vector x, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>void N_VInv_Parallel(N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:294</i>
//	 */
//	@Mangling({"_Z15N_VInv_ParallelP17_generic_N_VectorP17_generic_N_Vector", "?N_VInv_Parallel@@YAXPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native void N_VInv_Parallel(_generic_N_Vector x, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>void N_VAddConst_Parallel(N_Vector, realtype, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:295</i>
//	 */
//	@Mangling({"_Z20N_VAddConst_ParallelP17_generic_N_VectordP17_generic_N_Vector", "?N_VAddConst_Parallel@@YAXPA17_generic_N_VectorNPA17_generic_N_Vector@Z"}) 
//	public static native void N_VAddConst_Parallel(_generic_N_Vector x, double b, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>realtype N_VDotProd_Parallel(N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:296</i>
//	 */
//	@Mangling({"_Z19N_VDotProd_ParallelP17_generic_N_VectorP17_generic_N_Vector", "?N_VDotProd_Parallel@@YANPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native double N_VDotProd_Parallel(_generic_N_Vector x, _generic_N_Vector y);
//	/**
//	 * Original signature : <code>realtype N_VMaxNorm_Parallel(N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:297</i>
//	 */
//	@Mangling({"_Z19N_VMaxNorm_ParallelP17_generic_N_Vector", "?N_VMaxNorm_Parallel@@YANPA17_generic_N_Vector@Z"}) 
//	public static native double N_VMaxNorm_Parallel(_generic_N_Vector x);
//	/**
//	 * Original signature : <code>realtype N_VWrmsNorm_Parallel(N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:298</i>
//	 */
//	@Mangling({"_Z20N_VWrmsNorm_ParallelP17_generic_N_VectorP17_generic_N_Vector", "?N_VWrmsNorm_Parallel@@YANPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native double N_VWrmsNorm_Parallel(_generic_N_Vector x, _generic_N_Vector w);
//	/**
//	 * Original signature : <code>realtype N_VWrmsNormMask_Parallel(N_Vector, N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:299</i>
//	 */
//	@Mangling({"_Z24N_VWrmsNormMask_ParallelP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_Vector", "?N_VWrmsNormMask_Parallel@@YANPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native double N_VWrmsNormMask_Parallel(_generic_N_Vector x, _generic_N_Vector w, _generic_N_Vector id);
//	/**
//	 * Original signature : <code>realtype N_VMin_Parallel(N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:300</i>
//	 */
//	@Mangling({"_Z15N_VMin_ParallelP17_generic_N_Vector", "?N_VMin_Parallel@@YANPA17_generic_N_Vector@Z"}) 
//	public static native double N_VMin_Parallel(_generic_N_Vector x);
//	/**
//	 * Original signature : <code>realtype N_VWL2Norm_Parallel(N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:301</i>
//	 */
//	@Mangling({"_Z19N_VWL2Norm_ParallelP17_generic_N_VectorP17_generic_N_Vector", "?N_VWL2Norm_Parallel@@YANPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native double N_VWL2Norm_Parallel(_generic_N_Vector x, _generic_N_Vector w);
//	/**
//	 * Original signature : <code>realtype N_VL1Norm_Parallel(N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:302</i>
//	 */
//	@Mangling({"_Z18N_VL1Norm_ParallelP17_generic_N_Vector", "?N_VL1Norm_Parallel@@YANPA17_generic_N_Vector@Z"}) 
//	public static native double N_VL1Norm_Parallel(_generic_N_Vector x);
//	/**
//	 * Original signature : <code>void N_VCompare_Parallel(realtype, N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:303</i>
//	 */
//	@Mangling({"_Z19N_VCompare_ParalleldP17_generic_N_VectorP17_generic_N_Vector", "?N_VCompare_Parallel@@YAXNPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native void N_VCompare_Parallel(double c, _generic_N_Vector x, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>int N_VInvTest_Parallel(N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:304</i>
//	 */
//	@Mangling({"_Z19N_VInvTest_ParallelP17_generic_N_VectorP17_generic_N_Vector", "?N_VInvTest_Parallel@@YAHPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native int N_VInvTest_Parallel(_generic_N_Vector x, _generic_N_Vector z);
//	/**
//	 * Original signature : <code>int N_VConstrMask_Parallel(N_Vector, N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:305</i>
//	 */
//	@Mangling({"_Z22N_VConstrMask_ParallelP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_Vector", "?N_VConstrMask_Parallel@@YAHPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native int N_VConstrMask_Parallel(_generic_N_Vector c, _generic_N_Vector x, _generic_N_Vector m);
//	/**
//	 * Original signature : <code>realtype N_VMinQuotient_Parallel(N_Vector, N_Vector)</code><br>
//	 * <i>native declaration : include\nvector\nvector_parallel.h:306</i>
//	 */
//	@Mangling({"_Z23N_VMinQuotient_ParallelP17_generic_N_VectorP17_generic_N_Vector", "?N_VMinQuotient_Parallel@@YANPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
//	public static native double N_VMinQuotient_Parallel(_generic_N_Vector num, _generic_N_Vector denom);
//	/**
//	 * Original signature : <code>N_Vector N_VNew_Serial(long int)</code><br>
//	 * <i>native declaration : include\nvector\nvector_serial.h:160</i>
//	 */
	@Mangling({"_Z13N_VNew_Seriall", "?N_VNew_Serial@@YAPA17_generic_N_VectorJ@Z"}) 
	public static native _generic_N_Vector N_VNew_Serial(int vec_length);
	/**
	 * Original signature : <code>N_Vector N_VNewEmpty_Serial(long int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:171</i>
	 */
	@Mangling({"_Z18N_VNewEmpty_Seriall", "?N_VNewEmpty_Serial@@YAPA17_generic_N_VectorJ@Z"}) 
	public static native _generic_N_Vector N_VNewEmpty_Serial(int vec_length);
	/**
	 * Original signature : <code>N_Vector N_VMake_Serial(long int, realtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:182</i><br>
	 * @deprecated use the safer methods {@link #N_VMake_Serial(int, java.nio.DoubleBuffer)} and {@link #N_VMake_Serial(int, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Mangling({"_Z14N_VMake_SeriallPd", "?N_VMake_Serial@@YAPA17_generic_N_VectorJPAN@Z"}) 
	@Deprecated 
	public static native _generic_N_Vector N_VMake_Serial(int vec_length, DoubleByReference v_data);
	/**
	 * Original signature : <code>N_Vector N_VMake_Serial(long int, realtype*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:182</i>
	 */
	@Mangling({"_Z14N_VMake_SeriallPd", "?N_VMake_Serial@@YAPA17_generic_N_VectorJPAN@Z"}) 
	public static native _generic_N_Vector N_VMake_Serial(int vec_length, DoubleBuffer v_data);
	/**
	 * Original signature : <code>N_Vector* N_VCloneVectorArray_Serial(int, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:193</i>
	 */
	@Mangling({"_Z26N_VCloneVectorArray_SerialiP17_generic_N_Vector", "?N_VCloneVectorArray_Serial@@YAPAPA17_generic_N_VectorHPA17_generic_N_Vector@Z"}) 
	public static native _generic_N_Vector.ByReference N_VCloneVectorArray_Serial(int count, _generic_N_Vector w);
	/**
	 * Original signature : <code>N_Vector* N_VCloneVectorArrayEmpty_Serial(int, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:204</i>
	 */
	@Mangling({"_Z31N_VCloneVectorArrayEmpty_SerialiP17_generic_N_Vector", "?N_VCloneVectorArrayEmpty_Serial@@YAPAPA17_generic_N_VectorHPA17_generic_N_Vector@Z"}) 
	public static native _generic_N_Vector.ByReference N_VCloneVectorArrayEmpty_Serial(int count, _generic_N_Vector w);
	/**
	 * Original signature : <code>void N_VDestroyVectorArray_Serial(N_Vector*, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:215</i><br>
	 * @deprecated use the safer method {@link #N_VDestroyVectorArray_Serial(sundials._generic_N_Vector.ByReference[], int)} instead
	 */
	@Mangling({"_Z28N_VDestroyVectorArray_SerialPP17_generic_N_Vectori", "?N_VDestroyVectorArray_Serial@@YAXPAPA17_generic_N_VectorH@Z"}) 
	@Deprecated 
	public static native void N_VDestroyVectorArray_Serial(PointerByReference vs, int count);
	/**
	 * Original signature : <code>void N_VDestroyVectorArray_Serial(N_Vector*, int)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:215</i>
	 */
	@Mangling({"_Z28N_VDestroyVectorArray_SerialPP17_generic_N_Vectori", "?N_VDestroyVectorArray_Serial@@YAXPAPA17_generic_N_VectorH@Z"}) 
	public static native void N_VDestroyVectorArray_Serial(_generic_N_Vector.ByReference vs, int count);
	/**
	 * Original signature : <code>void N_VPrint_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:225</i>
	 */
	@Mangling({"_Z15N_VPrint_SerialP17_generic_N_Vector", "?N_VPrint_Serial@@YAXPA17_generic_N_Vector@Z"}) 
	public static native void N_VPrint_Serial(_generic_N_Vector v);
	/**
	 * Original signature : <code>N_Vector N_VCloneEmpty_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:233</i>
	 */
	@Mangling({"_Z20N_VCloneEmpty_SerialP17_generic_N_Vector", "?N_VCloneEmpty_Serial@@YAPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native _generic_N_Vector N_VCloneEmpty_Serial(_generic_N_Vector w);
	/**
	 * Original signature : <code>N_Vector N_VClone_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:234</i>
	 */
	@Mangling({"_Z15N_VClone_SerialP17_generic_N_Vector", "?N_VClone_Serial@@YAPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native _generic_N_Vector N_VClone_Serial(_generic_N_Vector w);
	/**
	 * Original signature : <code>void N_VDestroy_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:235</i>
	 */
	@Mangling({"_Z17N_VDestroy_SerialP17_generic_N_Vector", "?N_VDestroy_Serial@@YAXPA17_generic_N_Vector@Z"}) 
	public static native void N_VDestroy_Serial(_generic_N_Vector v);
	/**
	 * Original signature : <code>void N_VSpace_Serial(N_Vector, long int*, long int*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:236</i><br>
	 * @deprecated use the safer methods {@link #N_VSpace_Serial(sundials._generic_N_Vector, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #N_VSpace_Serial(sundials._generic_N_Vector, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z15N_VSpace_SerialP17_generic_N_VectorPlPl", "?N_VSpace_Serial@@YAXPA17_generic_N_VectorPAJPAJ@Z"}) 
	@Deprecated 
	public static native void N_VSpace_Serial(_generic_N_Vector v, IntByReference lrw, IntByReference liw);
	/**
	 * Original signature : <code>void N_VSpace_Serial(N_Vector, long int*, long int*)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:236</i>
	 */
	@Mangling({"_Z15N_VSpace_SerialP17_generic_N_VectorPlPl", "?N_VSpace_Serial@@YAXPA17_generic_N_VectorPAJPAJ@Z"}) 
	public static native void N_VSpace_Serial(_generic_N_Vector v, IntBuffer lrw, IntBuffer liw);
	/**
	 * Original signature : <code>realtype* N_VGetArrayPointer_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:237</i>
	 */
	@Mangling({"_Z25N_VGetArrayPointer_SerialP17_generic_N_Vector", "?N_VGetArrayPointer_Serial@@YAPANPA17_generic_N_Vector@Z"}) 
	public static native DoubleByReference N_VGetArrayPointer_Serial(_generic_N_Vector v);
	/**
	 * Original signature : <code>void N_VSetArrayPointer_Serial(realtype*, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:238</i><br>
	 * @deprecated use the safer methods {@link #N_VSetArrayPointer_Serial(java.nio.DoubleBuffer, sundials._generic_N_Vector)} and {@link #N_VSetArrayPointer_Serial(com.sun.jna.ptr.DoubleByReference, sundials._generic_N_Vector)} instead
	 */
	@Mangling({"_Z25N_VSetArrayPointer_SerialPdP17_generic_N_Vector", "?N_VSetArrayPointer_Serial@@YAXPANPA17_generic_N_Vector@Z"}) 
	@Deprecated 
	public static native void N_VSetArrayPointer_Serial(DoubleByReference v_data, _generic_N_Vector v);
	/**
	 * Original signature : <code>void N_VSetArrayPointer_Serial(realtype*, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:238</i>
	 */
	@Mangling({"_Z25N_VSetArrayPointer_SerialPdP17_generic_N_Vector", "?N_VSetArrayPointer_Serial@@YAXPANPA17_generic_N_Vector@Z"}) 
	public static native void N_VSetArrayPointer_Serial(DoubleBuffer v_data, _generic_N_Vector v);
	/**
	 * Original signature : <code>void N_VLinearSum_Serial(realtype, N_Vector, realtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:239</i>
	 */
	@Mangling({"_Z19N_VLinearSum_SerialdP17_generic_N_VectordP17_generic_N_VectorP17_generic_N_Vector", "?N_VLinearSum_Serial@@YAXNPA17_generic_N_VectorNPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native void N_VLinearSum_Serial(double a, _generic_N_Vector x, double b, _generic_N_Vector y, _generic_N_Vector z);
	/**
	 * Original signature : <code>void N_VConst_Serial(realtype, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:240</i>
	 */
	@Mangling({"_Z15N_VConst_SerialdP17_generic_N_Vector", "?N_VConst_Serial@@YAXNPA17_generic_N_Vector@Z"}) 
	public static native void N_VConst_Serial(double c, _generic_N_Vector z);
	/**
	 * Original signature : <code>void N_VProd_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:241</i>
	 */
	@Mangling({"_Z14N_VProd_SerialP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_Vector", "?N_VProd_Serial@@YAXPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native void N_VProd_Serial(_generic_N_Vector x, _generic_N_Vector y, _generic_N_Vector z);
	/**
	 * Original signature : <code>void N_VDiv_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:242</i>
	 */
	@Mangling({"_Z13N_VDiv_SerialP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_Vector", "?N_VDiv_Serial@@YAXPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native void N_VDiv_Serial(_generic_N_Vector x, _generic_N_Vector y, _generic_N_Vector z);
	/**
	 * Original signature : <code>void N_VScale_Serial(realtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:243</i>
	 */
	@Mangling({"_Z15N_VScale_SerialdP17_generic_N_VectorP17_generic_N_Vector", "?N_VScale_Serial@@YAXNPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native void N_VScale_Serial(double c, _generic_N_Vector x, _generic_N_Vector z);
	/**
	 * Original signature : <code>void N_VAbs_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:244</i>
	 */
	@Mangling({"_Z13N_VAbs_SerialP17_generic_N_VectorP17_generic_N_Vector", "?N_VAbs_Serial@@YAXPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native void N_VAbs_Serial(_generic_N_Vector x, _generic_N_Vector z);
	/**
	 * Original signature : <code>void N_VInv_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:245</i>
	 */
	@Mangling({"_Z13N_VInv_SerialP17_generic_N_VectorP17_generic_N_Vector", "?N_VInv_Serial@@YAXPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native void N_VInv_Serial(_generic_N_Vector x, _generic_N_Vector z);
	/**
	 * Original signature : <code>void N_VAddConst_Serial(N_Vector, realtype, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:246</i>
	 */
	@Mangling({"_Z18N_VAddConst_SerialP17_generic_N_VectordP17_generic_N_Vector", "?N_VAddConst_Serial@@YAXPA17_generic_N_VectorNPA17_generic_N_Vector@Z"}) 
	public static native void N_VAddConst_Serial(_generic_N_Vector x, double b, _generic_N_Vector z);
	/**
	 * Original signature : <code>realtype N_VDotProd_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:247</i>
	 */
	@Mangling({"_Z17N_VDotProd_SerialP17_generic_N_VectorP17_generic_N_Vector", "?N_VDotProd_Serial@@YANPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native double N_VDotProd_Serial(_generic_N_Vector x, _generic_N_Vector y);
	/**
	 * Original signature : <code>realtype N_VMaxNorm_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:248</i>
	 */
	@Mangling({"_Z17N_VMaxNorm_SerialP17_generic_N_Vector", "?N_VMaxNorm_Serial@@YANPA17_generic_N_Vector@Z"}) 
	public static native double N_VMaxNorm_Serial(_generic_N_Vector x);
	/**
	 * Original signature : <code>realtype N_VWrmsNorm_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:249</i>
	 */
	@Mangling({"_Z18N_VWrmsNorm_SerialP17_generic_N_VectorP17_generic_N_Vector", "?N_VWrmsNorm_Serial@@YANPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native double N_VWrmsNorm_Serial(_generic_N_Vector x, _generic_N_Vector w);
	/**
	 * Original signature : <code>realtype N_VWrmsNormMask_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:250</i>
	 */
	@Mangling({"_Z22N_VWrmsNormMask_SerialP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_Vector", "?N_VWrmsNormMask_Serial@@YANPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native double N_VWrmsNormMask_Serial(_generic_N_Vector x, _generic_N_Vector w, _generic_N_Vector id);
	/**
	 * Original signature : <code>realtype N_VMin_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:251</i>
	 */
	@Mangling({"_Z13N_VMin_SerialP17_generic_N_Vector", "?N_VMin_Serial@@YANPA17_generic_N_Vector@Z"}) 
	public static native double N_VMin_Serial(_generic_N_Vector x);
	/**
	 * Original signature : <code>realtype N_VWL2Norm_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:252</i>
	 */
	@Mangling({"_Z17N_VWL2Norm_SerialP17_generic_N_VectorP17_generic_N_Vector", "?N_VWL2Norm_Serial@@YANPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native double N_VWL2Norm_Serial(_generic_N_Vector x, _generic_N_Vector w);
	/**
	 * Original signature : <code>realtype N_VL1Norm_Serial(N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:253</i>
	 */
	@Mangling({"_Z16N_VL1Norm_SerialP17_generic_N_Vector", "?N_VL1Norm_Serial@@YANPA17_generic_N_Vector@Z"}) 
	public static native double N_VL1Norm_Serial(_generic_N_Vector x);
	/**
	 * Original signature : <code>void N_VCompare_Serial(realtype, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:254</i>
	 */
	@Mangling({"_Z17N_VCompare_SerialdP17_generic_N_VectorP17_generic_N_Vector", "?N_VCompare_Serial@@YAXNPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native void N_VCompare_Serial(double c, _generic_N_Vector x, _generic_N_Vector z);
	/**
	 * Original signature : <code>int N_VInvTest_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:255</i>
	 */
	@Mangling({"_Z17N_VInvTest_SerialP17_generic_N_VectorP17_generic_N_Vector", "?N_VInvTest_Serial@@YAHPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native int N_VInvTest_Serial(_generic_N_Vector x, _generic_N_Vector z);
	/**
	 * Original signature : <code>int N_VConstrMask_Serial(N_Vector, N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:256</i>
	 */
	@Mangling({"_Z20N_VConstrMask_SerialP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_Vector", "?N_VConstrMask_Serial@@YAHPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native int N_VConstrMask_Serial(_generic_N_Vector c, _generic_N_Vector x, _generic_N_Vector m);
	/**
	 * Original signature : <code>realtype N_VMinQuotient_Serial(N_Vector, N_Vector)</code><br>
	 * <i>native declaration : include\nvector\nvector_serial.h:257</i>
	 */
	@Mangling({"_Z21N_VMinQuotient_SerialP17_generic_N_VectorP17_generic_N_Vector", "?N_VMinQuotient_Serial@@YANPA17_generic_N_VectorPA17_generic_N_Vector@Z"}) 
	public static native double N_VMinQuotient_Serial(_generic_N_Vector num, _generic_N_Vector denom);
	/// Undefined type
	public static interface MPI_Comm {
		
	};
}
