package fit.jvode.jna.sundials;
import com.ochafik.lang.jnaerator.runtime.Structure;
/**
 * <i>native declaration : include\sundials\sundials_spbcgs.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SpbcgMem_struct extends Structure<SpbcgMem_struct, SpbcgMem_struct.ByValue, SpbcgMem_struct.ByReference > {
	public int l_max;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference r_star;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference r;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference p;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference q;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference u;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference Ap;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference vtemp;
	public SpbcgMem_struct() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"l_max", "r_star", "r", "p", "q", "u", "Ap", "vtemp"});
	}
	/**
	 * @param r_star C type : N_Vector<br>
	 * @param r C type : N_Vector<br>
	 * @param p C type : N_Vector<br>
	 * @param q C type : N_Vector<br>
	 * @param u C type : N_Vector<br>
	 * @param Ap C type : N_Vector<br>
	 * @param vtemp C type : N_Vector
	 */
	public SpbcgMem_struct(int l_max, _generic_N_Vector.ByReference r_star, _generic_N_Vector.ByReference r, _generic_N_Vector.ByReference p, _generic_N_Vector.ByReference q, _generic_N_Vector.ByReference u, _generic_N_Vector.ByReference Ap, _generic_N_Vector.ByReference vtemp) {
		super();
		this.l_max = l_max;
		this.r_star = r_star;
		this.r = r;
		this.p = p;
		this.q = q;
		this.u = u;
		this.Ap = Ap;
		this.vtemp = vtemp;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected SpbcgMem_struct newInstance() { return new SpbcgMem_struct(); }
	public static SpbcgMem_struct[] newArray(int arrayLength) {
		return Structure.newArray(SpbcgMem_struct.class, arrayLength);
	}
	public static class ByReference extends SpbcgMem_struct implements Structure.ByReference {
		
	};
	public static class ByValue extends SpbcgMem_struct implements Structure.ByValue {
		
	};
}
