package fit.jvode.jna.sundials;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.ptr.PointerByReference;
/**
 * <i>native declaration : include\sundials\sundials_sptfqmr.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SptfqmrMemRec extends Structure<SptfqmrMemRec, SptfqmrMemRec.ByValue, SptfqmrMemRec.ByReference > {
	public int l_max;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference r_star;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference q;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference d;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference v;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference p;
	/// C type : N_Vector*
	public PointerByReference r;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference u;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference vtemp1;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference vtemp2;
	/// C type : N_Vector
	public _generic_N_Vector.ByReference vtemp3;
	public SptfqmrMemRec() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"l_max", "r_star", "q", "d", "v", "p", "r", "u", "vtemp1", "vtemp2", "vtemp3"});
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected SptfqmrMemRec newInstance() { return new SptfqmrMemRec(); }
	public static SptfqmrMemRec[] newArray(int arrayLength) {
		return Structure.newArray(SptfqmrMemRec.class, arrayLength);
	}
	public static class ByReference extends SptfqmrMemRec implements Structure.ByReference {
		
	};
	public static class ByValue extends SptfqmrMemRec implements Structure.ByValue {
		
	};
}
