package fit.jvode.bridj.sundials;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : include\sundials\sundials_direct.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */

public class _DlsMat extends StructObject {
	public _DlsMat() {
		super();
	}
	public _DlsMat(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public int type() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public _DlsMat type(int type) {
		this.io.setIntField(this, 0, type);
		return this;
	}
	@Field(1) 
	public int M() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public _DlsMat M(int M) {
		this.io.setIntField(this, 1, M);
		return this;
	}
	@Field(2) 
	public int N() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public _DlsMat N(int N) {
		this.io.setIntField(this, 2, N);
		return this;
	}
	@Field(3) 
	public int ldim() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public _DlsMat ldim(int ldim) {
		this.io.setIntField(this, 3, ldim);
		return this;
	}
	@Field(4) 
	public int mu() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public _DlsMat mu(int mu) {
		this.io.setIntField(this, 4, mu);
		return this;
	}
	@Field(5) 
	public int ml() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public _DlsMat ml(int ml) {
		this.io.setIntField(this, 5, ml);
		return this;
	}
	@Field(6) 
	public int s_mu() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public _DlsMat s_mu(int s_mu) {
		this.io.setIntField(this, 6, s_mu);
		return this;
	}
	/// C type : realtype*
	@Field(7) 
	public Pointer<Double > data() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : realtype*
	@Field(7) 
	public _DlsMat data(Pointer<Double > data) {
		this.io.setPointerField(this, 7, data);
		return this;
	}
	@Field(8) 
	public int ldata() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public _DlsMat ldata(int ldata) {
		this.io.setIntField(this, 8, ldata);
		return this;
	}
	/// C type : realtype**
	@Field(9) 
	public Pointer<Pointer<Double > > cols() {
		return this.io.getPointerField(this, 9);
	}
	/// C type : realtype**
	@Field(9) 
	public _DlsMat cols(Pointer<Pointer<Double > > cols) {
		this.io.setPointerField(this, 9, cols);
		return this;
	}
}
