package fit.jvode.jna.cvode;
import com.ochafik.lang.jnaerator.runtime.LibraryExtractor;
import com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper;
import com.ochafik.lang.jnaerator.runtime.Mangling;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.DoubleByReference;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.DoubleBuffer;
import java.nio.IntBuffer;

import fit.jvode.jna.sundials.*;
/**
 * JNA Wrapper for library <b>cvode</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvodeLibrary implements Library {
	public static final String JNA_LIBRARY_NAME = LibraryExtractor.getLibraryPath("sundials_cvode", true, CvodeLibrary.class);
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(CvodeLibrary.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	static {
		Native.register(CvodeLibrary.JNA_LIBRARY_NAME);
	}
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_NEWTON = (int)2;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_ILL_INPUT = (int)-22;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_TOO_MUCH_WORK = (int)-1;
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public static final int CVDLS_MEM_NULL = (int)-1;
	/// <i>native declaration : include\cvode\cvode_diag.h</i>
	public static final int CVDIAG_ILL_INPUT = (int)-3;
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public static final int CVDLS_JACFUNC_RECVR = (int)-6;
	/// <i>native declaration : include\cvode\cvode_diag.h</i>
	public static final int CVDIAG_LMEM_NULL = (int)-2;
	/// <i>native declaration : include\cvode\cvode_diag.h</i>
	public static final int CVDIAG_MEM_NULL = (int)-1;
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public static final int CVSPILS_PMEM_NULL = (int)-5;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_ROOT_RETURN = (int)2;
	/// <i>native declaration : include\cvode\cvode_diag.h</i>
	public static final int CVDIAG_RHSFUNC_UNRECVR = (int)-6;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_ERR_FAILURE = (int)-3;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_TSTOP_RETURN = (int)1;
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public static final int CVSPILS_ILL_INPUT = (int)-3;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_NO_MALLOC = (int)-23;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_ONE_STEP = (int)2;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_RTFUNC_FAIL = (int)-12;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_MEM_FAIL = (int)-20;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_BAD_K = (int)-24;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_ADAMS = (int)1;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_BAD_T = (int)-25;
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public static final int CVDLS_JACFUNC_UNRECVR = (int)-5;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_LSOLVE_FAIL = (int)-7;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_NORMAL = (int)1;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_MEM_NULL = (int)-21;
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public static final int CVSPILS_SUCCESS = (int)0;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_BAD_DKY = (int)-26;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_REPTD_RHSFUNC_ERR = (int)-10;
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public static final int CVDLS_MEM_FAIL = (int)-4;
	/// <i>native declaration : include\cvode\cvode_diag.h</i>
	public static final int CVDIAG_INV_FAIL = (int)-5;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_FUNCTIONAL = (int)1;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_CONV_FAILURE = (int)-4;
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public static final int CVDLS_SUCCESS = (int)0;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_WARNING = (int)99;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_BDF = (int)2;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_UNREC_RHSFUNC_ERR = (int)-11;
	/// <i>native declaration : include\cvode\cvode_diag.h</i>
	public static final int CVDIAG_RHSFUNC_RECVR = (int)-7;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_FIRST_RHSFUNC_ERR = (int)-9;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_LSETUP_FAIL = (int)-6;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_SUCCESS = (int)0;
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public static final int CVSPILS_MSBPRE = (int)50;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_TOO_MUCH_ACC = (int)-2;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_TOO_CLOSE = (int)-27;
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public static final int CVSPILS_MAXL = (int)5;
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public static final int CVSPILS_MEM_FAIL = (int)-4;
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public static final int CVDLS_LMEM_NULL = (int)-2;
	/// <i>native declaration : include\cvode\cvode_diag.h</i>
	public static final int CVDIAG_SUCCESS = (int)0;
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public static final int CVDLS_ILL_INPUT = (int)-3;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_RHSFUNC_FAIL = (int)-8;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public static final int CV_LINIT_FAIL = (int)-5;
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public static final int CVSPILS_MEM_NULL = (int)-1;
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public static final int CVSPILS_LMEM_NULL = (int)-2;
	/// <i>native declaration : include\cvode\cvode_diag.h</i>
	public static final int CVDIAG_MEM_FAIL = (int)-4;
	/// <i>native declaration : include\cvode\cvode.h</i>
	public interface CVRhsFn extends Callback {
		int apply(double t, _generic_N_Vector y, _generic_N_Vector ydot, Pointer user_data);
	};
	/// <i>native declaration : include\cvode\cvode.h</i>
	public interface CVRootFn extends Callback {
		int apply(double t, _generic_N_Vector y, DoubleByReference gout, Pointer user_data);
	};
	/// <i>native declaration : include\cvode\cvode.h</i>
	public interface CVEwtFn extends Callback {
		int apply(_generic_N_Vector y, _generic_N_Vector ewt, Pointer user_data);
	};
	/// <i>native declaration : include\cvode\cvode.h</i>
	public interface CVErrHandlerFn extends Callback {
		void apply(int error_code, Pointer module, Pointer function, Pointer msg, Pointer user_data);
	};
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public interface CVDlsDenseJacFn extends Callback {
		int apply(int N, double t, _generic_N_Vector y, _generic_N_Vector fy, _DlsMat Jac, Pointer user_data, _generic_N_Vector tmp1, _generic_N_Vector tmp2, _generic_N_Vector tmp3);
	};
	/// <i>native declaration : include\cvode\cvode_direct.h</i>
	public interface CVDlsBandJacFn extends Callback {
		int apply(int N, int mupper, int mlower, double t, _generic_N_Vector y, _generic_N_Vector fy, _DlsMat Jac, Pointer user_data, _generic_N_Vector tmp1, _generic_N_Vector tmp2, _generic_N_Vector tmp3);
	};
	/// <i>native declaration : include\cvode\cvode_bbdpre.h</i>
	public interface CVLocalFn extends Callback {
		int apply(int Nlocal, double t, _generic_N_Vector y, _generic_N_Vector g, Pointer user_data);
	};
	/// <i>native declaration : include\cvode\cvode_bbdpre.h</i>
	public interface CVCommFn extends Callback {
		int apply(int Nlocal, double t, _generic_N_Vector y, Pointer user_data);
	};
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public interface CVSpilsPrecSetupFn extends Callback {
		int apply(double t, _generic_N_Vector y, _generic_N_Vector fy, int jok, IntByReference jcurPtr, double gamma, Pointer user_data, _generic_N_Vector tmp1, _generic_N_Vector tmp2, _generic_N_Vector tmp3);
	};
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public interface CVSpilsPrecSolveFn extends Callback {
		int apply(double t, _generic_N_Vector y, _generic_N_Vector fy, _generic_N_Vector r, _generic_N_Vector z, double gamma, double delta, int lr, Pointer user_data, _generic_N_Vector tmp);
	};
	/// <i>native declaration : include\cvode\cvode_spils.h</i>
	public interface CVSpilsJacTimesVecFn extends Callback {
		int apply(_generic_N_Vector v, _generic_N_Vector Jv, double t, _generic_N_Vector y, _generic_N_Vector fy, Pointer user_data, _generic_N_Vector tmp);
	};
	/**
	 * Original signature : <code>void* CVodeCreate(int, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:251</i>
	 */
	@Mangling({"_Z11CVodeCreateii", "?CVodeCreate@@YAPAXHH@Z"}) 
	public static native Pointer CVodeCreate(int lmm, int iter);
	/**
	 * Original signature : <code>int CVodeSetErrHandlerFn(void*, CVErrHandlerFn, void*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:363</i>
	 */
	@Mangling({"_Z20CVodeSetErrHandlerFnPvPFviPKcPKcPcPvEPv", "?CVodeSetErrHandlerFn@@YAHPAXPFXHPADPADPADPAX@EPAX@Z"}) 
	public static native int CVodeSetErrHandlerFn(Pointer cvode_mem, CvodeLibrary.CVErrHandlerFn ehfun, Pointer eh_data);
	/**
	 * Original signature : <code>int CVodeSetErrFile(void*, FILE*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:364</i>
	 */
	@Mangling({"_Z15CVodeSetErrFilePvP4FILE", "?CVodeSetErrFile@@YAHPAXPA4FILE@Z"}) 
	public static native int CVodeSetErrFile(Pointer cvode_mem, Pointer errfp);
	/**
	 * Original signature : <code>int CVodeSetUserData(void*, void*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:365</i>
	 */
	@Mangling({"_Z16CVodeSetUserDataPvPv", "?CVodeSetUserData@@YAHPAXPAX@Z"}) 
	public static native int CVodeSetUserData(Pointer cvode_mem, Pointer user_data);
	/**
	 * Original signature : <code>int CVodeSetMaxOrd(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:366</i>
	 */
	@Mangling({"_Z14CVodeSetMaxOrdPvi", "?CVodeSetMaxOrd@@YAHPAXH@Z"}) 
	public static native int CVodeSetMaxOrd(Pointer cvode_mem, int maxord);
	/**
	 * Original signature : <code>int CVodeSetMaxNumSteps(void*, long int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:367</i>
	 */
	@Mangling({"_Z19CVodeSetMaxNumStepsPvl", "?CVodeSetMaxNumSteps@@YAHPAXJ@Z"}) 
	public static native int CVodeSetMaxNumSteps(Pointer cvode_mem, int mxsteps);
	/**
	 * Original signature : <code>int CVodeSetMaxHnilWarns(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:368</i>
	 */
	@Mangling({"_Z20CVodeSetMaxHnilWarnsPvi", "?CVodeSetMaxHnilWarns@@YAHPAXH@Z"}) 
	public static native int CVodeSetMaxHnilWarns(Pointer cvode_mem, int mxhnil);
	/**
	 * Original signature : <code>int CVodeSetStabLimDet(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:369</i>
	 */
	@Mangling({"_Z18CVodeSetStabLimDetPvi", "?CVodeSetStabLimDet@@YAHPAXH@Z"}) 
	public static native int CVodeSetStabLimDet(Pointer cvode_mem, int stldet);
	/**
	 * Original signature : <code>int CVodeSetInitStep(void*, realtype)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:370</i>
	 */
	@Mangling({"_Z16CVodeSetInitStepPvd", "?CVodeSetInitStep@@YAHPAXN@Z"}) 
	public static native int CVodeSetInitStep(Pointer cvode_mem, double hin);
	/**
	 * Original signature : <code>int CVodeSetMinStep(void*, realtype)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:371</i>
	 */
	@Mangling({"_Z15CVodeSetMinStepPvd", "?CVodeSetMinStep@@YAHPAXN@Z"}) 
	public static native int CVodeSetMinStep(Pointer cvode_mem, double hmin);
	/**
	 * Original signature : <code>int CVodeSetMaxStep(void*, realtype)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:372</i>
	 */
	@Mangling({"_Z15CVodeSetMaxStepPvd", "?CVodeSetMaxStep@@YAHPAXN@Z"}) 
	public static native int CVodeSetMaxStep(Pointer cvode_mem, double hmax);
	/**
	 * Original signature : <code>int CVodeSetStopTime(void*, realtype)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:373</i>
	 */
	@Mangling({"_Z16CVodeSetStopTimePvd", "?CVodeSetStopTime@@YAHPAXN@Z"}) 
	public static native int CVodeSetStopTime(Pointer cvode_mem, double tstop);
	/**
	 * Original signature : <code>int CVodeSetMaxErrTestFails(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:374</i>
	 */
	@Mangling({"_Z23CVodeSetMaxErrTestFailsPvi", "?CVodeSetMaxErrTestFails@@YAHPAXH@Z"}) 
	public static native int CVodeSetMaxErrTestFails(Pointer cvode_mem, int maxnef);
	/**
	 * Original signature : <code>int CVodeSetMaxNonlinIters(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:375</i>
	 */
	@Mangling({"_Z22CVodeSetMaxNonlinItersPvi", "?CVodeSetMaxNonlinIters@@YAHPAXH@Z"}) 
	public static native int CVodeSetMaxNonlinIters(Pointer cvode_mem, int maxcor);
	/**
	 * Original signature : <code>int CVodeSetMaxConvFails(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:376</i>
	 */
	@Mangling({"_Z20CVodeSetMaxConvFailsPvi", "?CVodeSetMaxConvFails@@YAHPAXH@Z"}) 
	public static native int CVodeSetMaxConvFails(Pointer cvode_mem, int maxncf);
	/**
	 * Original signature : <code>int CVodeSetNonlinConvCoef(void*, realtype)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:377</i>
	 */
	@Mangling({"_Z22CVodeSetNonlinConvCoefPvd", "?CVodeSetNonlinConvCoef@@YAHPAXN@Z"}) 
	public static native int CVodeSetNonlinConvCoef(Pointer cvode_mem, double nlscoef);
	/**
	 * Original signature : <code>int CVodeSetIterType(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:379</i>
	 */
	@Mangling({"_Z16CVodeSetIterTypePvi", "?CVodeSetIterType@@YAHPAXH@Z"}) 
	public static native int CVodeSetIterType(Pointer cvode_mem, int iter);
	/**
	 * Original signature : <code>int CVodeSetRootDirection(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:381</i><br>
	 * @deprecated use the safer methods {@link #CVodeSetRootDirection(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeSetRootDirection(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z21CVodeSetRootDirectionPvPi", "?CVodeSetRootDirection@@YAHPAXPAH@Z"}) 
	@Deprecated 
	public static native int CVodeSetRootDirection(Pointer cvode_mem, IntByReference rootdir);
	/**
	 * Original signature : <code>int CVodeSetRootDirection(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:381</i>
	 */
	@Mangling({"_Z21CVodeSetRootDirectionPvPi", "?CVodeSetRootDirection@@YAHPAXPAH@Z"}) 
	public static native int CVodeSetRootDirection(Pointer cvode_mem, IntBuffer rootdir);
	/**
	 * Original signature : <code>int CVodeSetNoInactiveRootWarn(void*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:382</i>
	 */
	@Mangling({"_Z26CVodeSetNoInactiveRootWarnPv", "?CVodeSetNoInactiveRootWarn@@YAHPAX@Z"}) 
	public static native int CVodeSetNoInactiveRootWarn(Pointer cvode_mem);
	/**
	 * Original signature : <code>int CVodeInit(void*, CVRhsFn, realtype, N_Vector)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:408</i>
	 */
	@Mangling({"_Z9CVodeInitPvPFidP17_generic_N_VectorP17_generic_N_VectorPvEdP17_generic_N_Vector", "?CVodeInit@@YAHPAXPFHNPA17_generic_N_VectorPA17_generic_N_VectorPAX@ENPA17_generic_N_Vector@Z"}) 
	public static native int CVodeInit(Pointer cvode_mem, CvodeLibrary.CVRhsFn f, double t0, _generic_N_Vector y0);
	/**
	 * Original signature : <code>int CVodeReInit(void*, realtype, N_Vector)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:444</i>
	 */
	@Mangling({"_Z11CVodeReInitPvdP17_generic_N_Vector", "?CVodeReInit@@YAHPAXNPA17_generic_N_Vector@Z"}) 
	public static native int CVodeReInit(Pointer cvode_mem, double t0, _generic_N_Vector y0);
	/**
	 * Original signature : <code>int CVodeSStolerances(void*, realtype, realtype)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:485</i>
	 */
	@Mangling({"_Z17CVodeSStolerancesPvdd", "?CVodeSStolerances@@YAHPAXNN@Z"}) 
	public static native int CVodeSStolerances(Pointer cvode_mem, double reltol, double abstol);
	/**
	 * Original signature : <code>int CVodeSVtolerances(void*, realtype, N_Vector)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:486</i>
	 */
	@Mangling({"_Z17CVodeSVtolerancesPvdP17_generic_N_Vector", "?CVodeSVtolerances@@YAHPAXNPA17_generic_N_Vector@Z"}) 
	public static native int CVodeSVtolerances(Pointer cvode_mem, double reltol, _generic_N_Vector abstol);
	/**
	 * Original signature : <code>int CVodeWFtolerances(void*, CVEwtFn)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:487</i>
	 */
	@Mangling({"_Z17CVodeWFtolerancesPvPFiP17_generic_N_VectorP17_generic_N_VectorPvE", "?CVodeWFtolerances@@YAHPAXPFHPA17_generic_N_VectorPA17_generic_N_VectorPAX@E@Z"}) 
	public static native int CVodeWFtolerances(Pointer cvode_mem, CvodeLibrary.CVEwtFn efun);
	/**
	 * Original signature : <code>int CVodeRootInit(void*, int, CVRootFn)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:518</i>
	 */
	@Mangling({"_Z13CVodeRootInitPviPFidP17_generic_N_VectorPdPvE", "?CVodeRootInit@@YAHPAXHPFHNPA17_generic_N_VectorPANPAX@E@Z"}) 
	public static native int CVodeRootInit(Pointer cvode_mem, int nrtfn, CvodeLibrary.CVRootFn g);
	/**
	 * Original signature : <code>int CVode(void*, realtype, N_Vector, realtype*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:608</i><br>
	 * @deprecated use the safer methods {@link #CVode(com.sun.jna.Pointer, double, sundials._generic_N_Vector, java.nio.DoubleBuffer, int)} and {@link #CVode(com.sun.jna.Pointer, double, sundials._generic_N_Vector, com.sun.jna.ptr.DoubleByReference, int)} instead
	 */
	@Mangling({"_Z5CVodePvdP17_generic_N_VectorPdi", "?CVode@@YAHPAXNPA17_generic_N_VectorPANH@Z"}) 
	@Deprecated 
	public static native int CVode(Pointer cvode_mem, double tout, _generic_N_Vector yout, DoubleByReference tret, int itask);
	/**
	 * Original signature : <code>int CVode(void*, realtype, N_Vector, realtype*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:608</i>
	 */
	@Mangling({"_Z5CVodePvdP17_generic_N_VectorPdi", "?CVode@@YAHPAXNPA17_generic_N_VectorPANH@Z"}) 
	public static native int CVode(Pointer cvode_mem, double tout, _generic_N_Vector yout, DoubleBuffer tret, int itask);
	/**
	 * Original signature : <code>int CVodeGetDky(void*, realtype, int, N_Vector)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:649</i>
	 */
	@Mangling({"_Z11CVodeGetDkyPvdiP17_generic_N_Vector", "?CVodeGetDky@@YAHPAXNHPA17_generic_N_Vector@Z"}) 
	public static native int CVodeGetDky(Pointer cvode_mem, double t, int k, _generic_N_Vector dky);
	/**
	 * Original signature : <code>int CVodeGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:705</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetWorkSpace(com.sun.jna.Pointer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #CVodeGetWorkSpace(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z17CVodeGetWorkSpacePvPlPl", "?CVodeGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetWorkSpace(Pointer cvode_mem, IntByReference lenrw, IntByReference leniw);
	/**
	 * Original signature : <code>int CVodeGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:705</i>
	 */
	@Mangling({"_Z17CVodeGetWorkSpacePvPlPl", "?CVodeGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	public static native int CVodeGetWorkSpace(Pointer cvode_mem, IntBuffer lenrw, IntBuffer leniw);
	/**
	 * Original signature : <code>int CVodeGetNumSteps(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:706</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNumSteps(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetNumSteps(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z16CVodeGetNumStepsPvPl", "?CVodeGetNumSteps@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNumSteps(Pointer cvode_mem, IntByReference nsteps);
	/**
	 * Original signature : <code>int CVodeGetNumSteps(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:706</i>
	 */
	@Mangling({"_Z16CVodeGetNumStepsPvPl", "?CVodeGetNumSteps@@YAHPAXPAJ@Z"}) 
	public static native int CVodeGetNumSteps(Pointer cvode_mem, IntBuffer nsteps);
	/**
	 * Original signature : <code>int CVodeGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:707</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNumRhsEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetNumRhsEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z19CVodeGetNumRhsEvalsPvPl", "?CVodeGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNumRhsEvals(Pointer cvode_mem, IntByReference nfevals);
	/**
	 * Original signature : <code>int CVodeGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:707</i>
	 */
	@Mangling({"_Z19CVodeGetNumRhsEvalsPvPl", "?CVodeGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVodeGetNumRhsEvals(Pointer cvode_mem, IntBuffer nfevals);
	/**
	 * Original signature : <code>int CVodeGetNumLinSolvSetups(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:708</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNumLinSolvSetups(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetNumLinSolvSetups(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z24CVodeGetNumLinSolvSetupsPvPl", "?CVodeGetNumLinSolvSetups@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNumLinSolvSetups(Pointer cvode_mem, IntByReference nlinsetups);
	/**
	 * Original signature : <code>int CVodeGetNumLinSolvSetups(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:708</i>
	 */
	@Mangling({"_Z24CVodeGetNumLinSolvSetupsPvPl", "?CVodeGetNumLinSolvSetups@@YAHPAXPAJ@Z"}) 
	public static native int CVodeGetNumLinSolvSetups(Pointer cvode_mem, IntBuffer nlinsetups);
	/**
	 * Original signature : <code>int CVodeGetNumErrTestFails(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:709</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNumErrTestFails(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetNumErrTestFails(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z23CVodeGetNumErrTestFailsPvPl", "?CVodeGetNumErrTestFails@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNumErrTestFails(Pointer cvode_mem, IntByReference netfails);
	/**
	 * Original signature : <code>int CVodeGetNumErrTestFails(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:709</i>
	 */
	@Mangling({"_Z23CVodeGetNumErrTestFailsPvPl", "?CVodeGetNumErrTestFails@@YAHPAXPAJ@Z"}) 
	public static native int CVodeGetNumErrTestFails(Pointer cvode_mem, IntBuffer netfails);
	/**
	 * Original signature : <code>int CVodeGetLastOrder(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:710</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetLastOrder(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetLastOrder(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z17CVodeGetLastOrderPvPi", "?CVodeGetLastOrder@@YAHPAXPAH@Z"}) 
	@Deprecated 
	public static native int CVodeGetLastOrder(Pointer cvode_mem, IntByReference qlast);
	/**
	 * Original signature : <code>int CVodeGetLastOrder(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:710</i>
	 */
	@Mangling({"_Z17CVodeGetLastOrderPvPi", "?CVodeGetLastOrder@@YAHPAXPAH@Z"}) 
	public static native int CVodeGetLastOrder(Pointer cvode_mem, IntBuffer qlast);
	/**
	 * Original signature : <code>int CVodeGetCurrentOrder(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:711</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetCurrentOrder(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetCurrentOrder(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z20CVodeGetCurrentOrderPvPi", "?CVodeGetCurrentOrder@@YAHPAXPAH@Z"}) 
	@Deprecated 
	public static native int CVodeGetCurrentOrder(Pointer cvode_mem, IntByReference qcur);
	/**
	 * Original signature : <code>int CVodeGetCurrentOrder(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:711</i>
	 */
	@Mangling({"_Z20CVodeGetCurrentOrderPvPi", "?CVodeGetCurrentOrder@@YAHPAXPAH@Z"}) 
	public static native int CVodeGetCurrentOrder(Pointer cvode_mem, IntBuffer qcur);
	/**
	 * Original signature : <code>int CVodeGetNumStabLimOrderReds(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:712</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNumStabLimOrderReds(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetNumStabLimOrderReds(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z27CVodeGetNumStabLimOrderRedsPvPl", "?CVodeGetNumStabLimOrderReds@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNumStabLimOrderReds(Pointer cvode_mem, IntByReference nslred);
	/**
	 * Original signature : <code>int CVodeGetNumStabLimOrderReds(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:712</i>
	 */
	@Mangling({"_Z27CVodeGetNumStabLimOrderRedsPvPl", "?CVodeGetNumStabLimOrderReds@@YAHPAXPAJ@Z"}) 
	public static native int CVodeGetNumStabLimOrderReds(Pointer cvode_mem, IntBuffer nslred);
	/**
	 * Original signature : <code>int CVodeGetActualInitStep(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:713</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetActualInitStep(com.sun.jna.Pointer, java.nio.DoubleBuffer)} and {@link #CVodeGetActualInitStep(com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Mangling({"_Z22CVodeGetActualInitStepPvPd", "?CVodeGetActualInitStep@@YAHPAXPAN@Z"}) 
	@Deprecated 
	public static native int CVodeGetActualInitStep(Pointer cvode_mem, DoubleByReference hinused);
	/**
	 * Original signature : <code>int CVodeGetActualInitStep(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:713</i>
	 */
	@Mangling({"_Z22CVodeGetActualInitStepPvPd", "?CVodeGetActualInitStep@@YAHPAXPAN@Z"}) 
	public static native int CVodeGetActualInitStep(Pointer cvode_mem, DoubleBuffer hinused);
	/**
	 * Original signature : <code>int CVodeGetLastStep(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:714</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetLastStep(com.sun.jna.Pointer, java.nio.DoubleBuffer)} and {@link #CVodeGetLastStep(com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Mangling({"_Z16CVodeGetLastStepPvPd", "?CVodeGetLastStep@@YAHPAXPAN@Z"}) 
	@Deprecated 
	public static native int CVodeGetLastStep(Pointer cvode_mem, DoubleByReference hlast);
	/**
	 * Original signature : <code>int CVodeGetLastStep(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:714</i>
	 */
	@Mangling({"_Z16CVodeGetLastStepPvPd", "?CVodeGetLastStep@@YAHPAXPAN@Z"}) 
	public static native int CVodeGetLastStep(Pointer cvode_mem, DoubleBuffer hlast);
	/**
	 * Original signature : <code>int CVodeGetCurrentStep(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:715</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetCurrentStep(com.sun.jna.Pointer, java.nio.DoubleBuffer)} and {@link #CVodeGetCurrentStep(com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Mangling({"_Z19CVodeGetCurrentStepPvPd", "?CVodeGetCurrentStep@@YAHPAXPAN@Z"}) 
	@Deprecated 
	public static native int CVodeGetCurrentStep(Pointer cvode_mem, DoubleByReference hcur);
	/**
	 * Original signature : <code>int CVodeGetCurrentStep(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:715</i>
	 */
	@Mangling({"_Z19CVodeGetCurrentStepPvPd", "?CVodeGetCurrentStep@@YAHPAXPAN@Z"}) 
	public static native int CVodeGetCurrentStep(Pointer cvode_mem, DoubleBuffer hcur);
	/**
	 * Original signature : <code>int CVodeGetCurrentTime(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:716</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetCurrentTime(com.sun.jna.Pointer, java.nio.DoubleBuffer)} and {@link #CVodeGetCurrentTime(com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Mangling({"_Z19CVodeGetCurrentTimePvPd", "?CVodeGetCurrentTime@@YAHPAXPAN@Z"}) 
	@Deprecated 
	public static native int CVodeGetCurrentTime(Pointer cvode_mem, DoubleByReference tcur);
	/**
	 * Original signature : <code>int CVodeGetCurrentTime(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:716</i>
	 */
	@Mangling({"_Z19CVodeGetCurrentTimePvPd", "?CVodeGetCurrentTime@@YAHPAXPAN@Z"}) 
	public static native int CVodeGetCurrentTime(Pointer cvode_mem, DoubleBuffer tcur);
	/**
	 * Original signature : <code>int CVodeGetTolScaleFactor(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:717</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetTolScaleFactor(com.sun.jna.Pointer, java.nio.DoubleBuffer)} and {@link #CVodeGetTolScaleFactor(com.sun.jna.Pointer, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Mangling({"_Z22CVodeGetTolScaleFactorPvPd", "?CVodeGetTolScaleFactor@@YAHPAXPAN@Z"}) 
	@Deprecated 
	public static native int CVodeGetTolScaleFactor(Pointer cvode_mem, DoubleByReference tolsfac);
	/**
	 * Original signature : <code>int CVodeGetTolScaleFactor(void*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:717</i>
	 */
	@Mangling({"_Z22CVodeGetTolScaleFactorPvPd", "?CVodeGetTolScaleFactor@@YAHPAXPAN@Z"}) 
	public static native int CVodeGetTolScaleFactor(Pointer cvode_mem, DoubleBuffer tolsfac);
	/**
	 * Original signature : <code>int CVodeGetErrWeights(void*, N_Vector)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:718</i>
	 */
	@Mangling({"_Z18CVodeGetErrWeightsPvP17_generic_N_Vector", "?CVodeGetErrWeights@@YAHPAXPA17_generic_N_Vector@Z"}) 
	public static native int CVodeGetErrWeights(Pointer cvode_mem, _generic_N_Vector eweight);
	/**
	 * Original signature : <code>int CVodeGetEstLocalErrors(void*, N_Vector)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:719</i>
	 */
	@Mangling({"_Z22CVodeGetEstLocalErrorsPvP17_generic_N_Vector", "?CVodeGetEstLocalErrors@@YAHPAXPA17_generic_N_Vector@Z"}) 
	public static native int CVodeGetEstLocalErrors(Pointer cvode_mem, _generic_N_Vector ele);
	/**
	 * Original signature : <code>int CVodeGetNumGEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:720</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNumGEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetNumGEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z17CVodeGetNumGEvalsPvPl", "?CVodeGetNumGEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNumGEvals(Pointer cvode_mem, IntByReference ngevals);
	/**
	 * Original signature : <code>int CVodeGetNumGEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:720</i>
	 */
	@Mangling({"_Z17CVodeGetNumGEvalsPvPl", "?CVodeGetNumGEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVodeGetNumGEvals(Pointer cvode_mem, IntBuffer ngevals);
	/**
	 * Original signature : <code>int CVodeGetRootInfo(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:721</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetRootInfo(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetRootInfo(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z16CVodeGetRootInfoPvPi", "?CVodeGetRootInfo@@YAHPAXPAH@Z"}) 
	@Deprecated 
	public static native int CVodeGetRootInfo(Pointer cvode_mem, IntByReference rootsfound);
	/**
	 * Original signature : <code>int CVodeGetRootInfo(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:721</i>
	 */
	@Mangling({"_Z16CVodeGetRootInfoPvPi", "?CVodeGetRootInfo@@YAHPAXPAH@Z"}) 
	public static native int CVodeGetRootInfo(Pointer cvode_mem, IntBuffer rootsfound);
	/**
	 * Original signature : <code>int CVodeGetIntegratorStats(void*, long int*, long int*, long int*, long int*, int*, int*, realtype*, realtype*, realtype*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:730</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetIntegratorStats(com.sun.jna.Pointer, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.DoubleBuffer, java.nio.DoubleBuffer, java.nio.DoubleBuffer, java.nio.DoubleBuffer)} and {@link #CVodeGetIntegratorStats(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Mangling({"_Z23CVodeGetIntegratorStatsPvPlPlPlPlPiPiPdPdPdPd", "?CVodeGetIntegratorStats@@YAHPAXPAJPAJPAJPAJPAHPAHPANPANPANPAN@Z"}) 
	@Deprecated 
	public static native int CVodeGetIntegratorStats(Pointer cvode_mem, IntByReference nsteps, IntByReference nfevals, IntByReference nlinsetups, IntByReference netfails, IntByReference qlast, IntByReference qcur, DoubleByReference hinused, DoubleByReference hlast, DoubleByReference hcur, DoubleByReference tcur);
	/**
	 * Original signature : <code>int CVodeGetIntegratorStats(void*, long int*, long int*, long int*, long int*, int*, int*, realtype*, realtype*, realtype*, realtype*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:730</i>
	 */
	@Mangling({"_Z23CVodeGetIntegratorStatsPvPlPlPlPlPiPiPdPdPdPd", "?CVodeGetIntegratorStats@@YAHPAXPAJPAJPAJPAJPAHPAHPANPANPANPAN@Z"}) 
	public static native int CVodeGetIntegratorStats(Pointer cvode_mem, IntBuffer nsteps, IntBuffer nfevals, IntBuffer nlinsetups, IntBuffer netfails, IntBuffer qlast, IntBuffer qcur, DoubleBuffer hinused, DoubleBuffer hlast, DoubleBuffer hcur, DoubleBuffer tcur);
	/**
	 * Original signature : <code>int CVodeGetNumNonlinSolvIters(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:750</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNumNonlinSolvIters(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetNumNonlinSolvIters(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z26CVodeGetNumNonlinSolvItersPvPl", "?CVodeGetNumNonlinSolvIters@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNumNonlinSolvIters(Pointer cvode_mem, IntByReference nniters);
	/**
	 * Original signature : <code>int CVodeGetNumNonlinSolvIters(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:750</i>
	 */
	@Mangling({"_Z26CVodeGetNumNonlinSolvItersPvPl", "?CVodeGetNumNonlinSolvIters@@YAHPAXPAJ@Z"}) 
	public static native int CVodeGetNumNonlinSolvIters(Pointer cvode_mem, IntBuffer nniters);
	/**
	 * Original signature : <code>int CVodeGetNumNonlinSolvConvFails(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:751</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNumNonlinSolvConvFails(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVodeGetNumNonlinSolvConvFails(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z30CVodeGetNumNonlinSolvConvFailsPvPl", "?CVodeGetNumNonlinSolvConvFails@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNumNonlinSolvConvFails(Pointer cvode_mem, IntByReference nncfails);
	/**
	 * Original signature : <code>int CVodeGetNumNonlinSolvConvFails(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:751</i>
	 */
	@Mangling({"_Z30CVodeGetNumNonlinSolvConvFailsPvPl", "?CVodeGetNumNonlinSolvConvFails@@YAHPAXPAJ@Z"}) 
	public static native int CVodeGetNumNonlinSolvConvFails(Pointer cvode_mem, IntBuffer nncfails);
	/**
	 * Original signature : <code>int CVodeGetNonlinSolvStats(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:760</i><br>
	 * @deprecated use the safer methods {@link #CVodeGetNonlinSolvStats(com.sun.jna.Pointer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #CVodeGetNonlinSolvStats(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z23CVodeGetNonlinSolvStatsPvPlPl", "?CVodeGetNonlinSolvStats@@YAHPAXPAJPAJ@Z"}) 
	@Deprecated 
	public static native int CVodeGetNonlinSolvStats(Pointer cvode_mem, IntByReference nniters, IntByReference nncfails);
	/**
	 * Original signature : <code>int CVodeGetNonlinSolvStats(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:760</i>
	 */
	@Mangling({"_Z23CVodeGetNonlinSolvStatsPvPlPl", "?CVodeGetNonlinSolvStats@@YAHPAXPAJPAJ@Z"}) 
	public static native int CVodeGetNonlinSolvStats(Pointer cvode_mem, IntBuffer nniters, IntBuffer nncfails);
	/**
	 * Original signature : <code>char* CVodeGetReturnFlagName(int)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:770</i>
	 */
	@Mangling({"_Z22CVodeGetReturnFlagNamei", "?CVodeGetReturnFlagName@@YAPADH@Z"}) 
	public static native Pointer CVodeGetReturnFlagName(int flag);
	/**
	 * Original signature : <code>void CVodeFree(void**)</code><br>
	 * <i>native declaration : include\cvode\cvode.h:782</i>
	 */
	@Mangling({"_Z9CVodeFreePPv", "?CVodeFree@@YAXPAPAX@Z"}) 
	public static native void CVodeFree(PointerByReference cvode_mem);
	/**
	 * Original signature : <code>int CVDlsSetDenseJacFn(void*, CVDlsDenseJacFn)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:239</i>
	 */
	@Mangling({"_Z18CVDlsSetDenseJacFnPvPFiidP17_generic_N_VectorP17_generic_N_VectorP7_DlsMatPvP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_VectorE", "?CVDlsSetDenseJacFn@@YAHPAXPFHHNPA17_generic_N_VectorPA17_generic_N_VectorPA7_DlsMatPAXPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@E@Z"}) 
	public static native int CVDlsSetDenseJacFn(Pointer cvode_mem, CvodeLibrary.CVDlsDenseJacFn jac);
	/**
	 * Original signature : <code>int CVDlsSetBandJacFn(void*, CVDlsBandJacFn)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:240</i>
	 */
	@Mangling({"_Z17CVDlsSetBandJacFnPvPFiiiidP17_generic_N_VectorP17_generic_N_VectorP7_DlsMatPvP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_VectorE", "?CVDlsSetBandJacFn@@YAHPAXPFHHHHNPA17_generic_N_VectorPA17_generic_N_VectorPA7_DlsMatPAXPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@E@Z"}) 
	public static native int CVDlsSetBandJacFn(Pointer cvode_mem, CvodeLibrary.CVDlsBandJacFn jac);
	/**
	 * Original signature : <code>int CVDlsGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:264</i><br>
	 * @deprecated use the safer methods {@link #CVDlsGetWorkSpace(com.sun.jna.Pointer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #CVDlsGetWorkSpace(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z17CVDlsGetWorkSpacePvPlPl", "?CVDlsGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	@Deprecated 
	public static native int CVDlsGetWorkSpace(Pointer cvode_mem, IntByReference lenrwLS, IntByReference leniwLS);
	/**
	 * Original signature : <code>int CVDlsGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:264</i>
	 */
	@Mangling({"_Z17CVDlsGetWorkSpacePvPlPl", "?CVDlsGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	public static native int CVDlsGetWorkSpace(Pointer cvode_mem, IntBuffer lenrwLS, IntBuffer leniwLS);
	/**
	 * Original signature : <code>int CVDlsGetNumJacEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:265</i><br>
	 * @deprecated use the safer methods {@link #CVDlsGetNumJacEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVDlsGetNumJacEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z19CVDlsGetNumJacEvalsPvPl", "?CVDlsGetNumJacEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVDlsGetNumJacEvals(Pointer cvode_mem, IntByReference njevals);
	/**
	 * Original signature : <code>int CVDlsGetNumJacEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:265</i>
	 */
	@Mangling({"_Z19CVDlsGetNumJacEvalsPvPl", "?CVDlsGetNumJacEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVDlsGetNumJacEvals(Pointer cvode_mem, IntBuffer njevals);
	/**
	 * Original signature : <code>int CVDlsGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:266</i><br>
	 * @deprecated use the safer methods {@link #CVDlsGetNumRhsEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVDlsGetNumRhsEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z19CVDlsGetNumRhsEvalsPvPl", "?CVDlsGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVDlsGetNumRhsEvals(Pointer cvode_mem, IntByReference nfevalsLS);
	/**
	 * Original signature : <code>int CVDlsGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:266</i>
	 */
	@Mangling({"_Z19CVDlsGetNumRhsEvalsPvPl", "?CVDlsGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVDlsGetNumRhsEvals(Pointer cvode_mem, IntBuffer nfevalsLS);
	/**
	 * Original signature : <code>int CVDlsGetLastFlag(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:267</i><br>
	 * @deprecated use the safer methods {@link #CVDlsGetLastFlag(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVDlsGetLastFlag(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z16CVDlsGetLastFlagPvPi", "?CVDlsGetLastFlag@@YAHPAXPAH@Z"}) 
	@Deprecated 
	public static native int CVDlsGetLastFlag(Pointer cvode_mem, IntByReference flag);
	/**
	 * Original signature : <code>int CVDlsGetLastFlag(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:267</i>
	 */
	@Mangling({"_Z16CVDlsGetLastFlagPvPi", "?CVDlsGetLastFlag@@YAHPAXPAH@Z"}) 
	public static native int CVDlsGetLastFlag(Pointer cvode_mem, IntBuffer flag);
	/**
	 * Original signature : <code>char* CVDlsGetReturnFlagName(int)</code><br>
	 * <i>native declaration : include\cvode\cvode_direct.h:276</i>
	 */
	@Mangling({"_Z22CVDlsGetReturnFlagNamei", "?CVDlsGetReturnFlagName@@YAPADH@Z"}) 
	public static native Pointer CVDlsGetReturnFlagName(int flag);
	/**
	 * Original signature : <code>int CVBand(void*, int, int, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_band.h:53</i>
	 */
	@Mangling({"_Z6CVBandPviii", "?CVBand@@YAHPAXHHH@Z"}) 
	public static native int CVBand(Pointer cvode_mem, int N, int mupper, int mlower);
	/**
	 * Original signature : <code>int CVBandPrecInit(void*, int, int, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_bandpre.h:111</i>
	 */
	@Mangling({"_Z14CVBandPrecInitPviii", "?CVBandPrecInit@@YAHPAXHHH@Z"}) 
	public static native int CVBandPrecInit(Pointer cvode_mem, int N, int mu, int ml);
	/**
	 * Original signature : <code>int CVBandPrecGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_bandpre.h:131</i><br>
	 * @deprecated use the safer methods {@link #CVBandPrecGetWorkSpace(com.sun.jna.Pointer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #CVBandPrecGetWorkSpace(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z22CVBandPrecGetWorkSpacePvPlPl", "?CVBandPrecGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	@Deprecated 
	public static native int CVBandPrecGetWorkSpace(Pointer cvode_mem, IntByReference lenrwLS, IntByReference leniwLS);
	/**
	 * Original signature : <code>int CVBandPrecGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_bandpre.h:131</i>
	 */
	@Mangling({"_Z22CVBandPrecGetWorkSpacePvPlPl", "?CVBandPrecGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	public static native int CVBandPrecGetWorkSpace(Pointer cvode_mem, IntBuffer lenrwLS, IntBuffer leniwLS);
	/**
	 * Original signature : <code>int CVBandPrecGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_bandpre.h:132</i><br>
	 * @deprecated use the safer methods {@link #CVBandPrecGetNumRhsEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVBandPrecGetNumRhsEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z24CVBandPrecGetNumRhsEvalsPvPl", "?CVBandPrecGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVBandPrecGetNumRhsEvals(Pointer cvode_mem, IntByReference nfevalsBP);
	/**
	 * Original signature : <code>int CVBandPrecGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_bandpre.h:132</i>
	 */
	@Mangling({"_Z24CVBandPrecGetNumRhsEvalsPvPl", "?CVBandPrecGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVBandPrecGetNumRhsEvals(Pointer cvode_mem, IntBuffer nfevalsBP);
	/**
	 * Original signature : <code>int CVBBDPrecInit(void*, int, int, int, int, int, realtype, CVLocalFn, CVCommFn)</code><br>
	 * <i>native declaration : include\cvode\cvode_bbdpre.h:212</i>
	 */
	@Mangling({"_Z13CVBBDPrecInitPviiiiidPFiidP17_generic_N_VectorP17_generic_N_VectorPvEPFiidP17_generic_N_VectorPvE", "?CVBBDPrecInit@@YAHPAXHHHHHNPFHHNPA17_generic_N_VectorPA17_generic_N_VectorPAX@EPFHHNPA17_generic_N_VectorPAX@E@Z"}) 
	public static native int CVBBDPrecInit(Pointer cvode_mem, int Nlocal, int mudq, int mldq, int mukeep, int mlkeep, double dqrely, CvodeLibrary.CVLocalFn gloc, CvodeLibrary.CVCommFn cfn);
	/**
	 * Original signature : <code>int CVBBDPrecReInit(void*, int, int, realtype)</code><br>
	 * <i>native declaration : include\cvode\cvode_bbdpre.h:240</i>
	 */
	@Mangling({"_Z15CVBBDPrecReInitPviid", "?CVBBDPrecReInit@@YAHPAXHHN@Z"}) 
	public static native int CVBBDPrecReInit(Pointer cvode_mem, int mudq, int mldq, double dqrely);
	/**
	 * Original signature : <code>int CVBBDPrecGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_bbdpre.h:259</i><br>
	 * @deprecated use the safer methods {@link #CVBBDPrecGetWorkSpace(com.sun.jna.Pointer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #CVBBDPrecGetWorkSpace(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z21CVBBDPrecGetWorkSpacePvPlPl", "?CVBBDPrecGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	@Deprecated 
	public static native int CVBBDPrecGetWorkSpace(Pointer cvode_mem, IntByReference lenrwLS, IntByReference leniwLS);
	/**
	 * Original signature : <code>int CVBBDPrecGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_bbdpre.h:259</i>
	 */
	@Mangling({"_Z21CVBBDPrecGetWorkSpacePvPlPl", "?CVBBDPrecGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	public static native int CVBBDPrecGetWorkSpace(Pointer cvode_mem, IntBuffer lenrwLS, IntBuffer leniwLS);
	/**
	 * Original signature : <code>int CVBBDPrecGetNumGfnEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_bbdpre.h:260</i><br>
	 * @deprecated use the safer methods {@link #CVBBDPrecGetNumGfnEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVBBDPrecGetNumGfnEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z23CVBBDPrecGetNumGfnEvalsPvPl", "?CVBBDPrecGetNumGfnEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVBBDPrecGetNumGfnEvals(Pointer cvode_mem, IntByReference ngevalsBBDP);
	/**
	 * Original signature : <code>int CVBBDPrecGetNumGfnEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_bbdpre.h:260</i>
	 */
	@Mangling({"_Z23CVBBDPrecGetNumGfnEvalsPvPl", "?CVBBDPrecGetNumGfnEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVBBDPrecGetNumGfnEvals(Pointer cvode_mem, IntBuffer ngevalsBBDP);
	/**
	 * Original signature : <code>int CVDense(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_dense.h:46</i>
	 */
	@Mangling({"_Z7CVDensePvi", "?CVDense@@YAHPAXH@Z"}) 
	public static native int CVDense(Pointer cvode_mem, int N);
	/**
	 * Original signature : <code>int CVDiag(void*)</code><br>
	 * <i>native declaration : include\cvode\cvode_diag.h:43</i>
	 */
	@Mangling({"_Z6CVDiagPv", "?CVDiag@@YAHPAX@Z"}) 
	public static native int CVDiag(Pointer cvode_mem);
	/**
	 * Original signature : <code>int CVDiagGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_diag.h:69</i><br>
	 * @deprecated use the safer methods {@link #CVDiagGetWorkSpace(com.sun.jna.Pointer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #CVDiagGetWorkSpace(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z18CVDiagGetWorkSpacePvPlPl", "?CVDiagGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	@Deprecated 
	public static native int CVDiagGetWorkSpace(Pointer cvode_mem, IntByReference lenrwLS, IntByReference leniwLS);
	/**
	 * Original signature : <code>int CVDiagGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_diag.h:69</i>
	 */
	@Mangling({"_Z18CVDiagGetWorkSpacePvPlPl", "?CVDiagGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	public static native int CVDiagGetWorkSpace(Pointer cvode_mem, IntBuffer lenrwLS, IntBuffer leniwLS);
	/**
	 * Original signature : <code>int CVDiagGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_diag.h:70</i><br>
	 * @deprecated use the safer methods {@link #CVDiagGetNumRhsEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVDiagGetNumRhsEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z20CVDiagGetNumRhsEvalsPvPl", "?CVDiagGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVDiagGetNumRhsEvals(Pointer cvode_mem, IntByReference nfevalsLS);
	/**
	 * Original signature : <code>int CVDiagGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_diag.h:70</i>
	 */
	@Mangling({"_Z20CVDiagGetNumRhsEvalsPvPl", "?CVDiagGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVDiagGetNumRhsEvals(Pointer cvode_mem, IntBuffer nfevalsLS);
	/**
	 * Original signature : <code>int CVDiagGetLastFlag(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_diag.h:71</i><br>
	 * @deprecated use the safer methods {@link #CVDiagGetLastFlag(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVDiagGetLastFlag(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z17CVDiagGetLastFlagPvPi", "?CVDiagGetLastFlag@@YAHPAXPAH@Z"}) 
	@Deprecated 
	public static native int CVDiagGetLastFlag(Pointer cvode_mem, IntByReference flag);
	/**
	 * Original signature : <code>int CVDiagGetLastFlag(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_diag.h:71</i>
	 */
	@Mangling({"_Z17CVDiagGetLastFlagPvPi", "?CVDiagGetLastFlag@@YAHPAXPAH@Z"}) 
	public static native int CVDiagGetLastFlag(Pointer cvode_mem, IntBuffer flag);
	/**
	 * Original signature : <code>char* CVDiagGetReturnFlagName(int)</code><br>
	 * <i>native declaration : include\cvode\cvode_diag.h:80</i>
	 */
	@Mangling({"_Z23CVDiagGetReturnFlagNamei", "?CVDiagGetReturnFlagName@@YAPADH@Z"}) 
	public static native Pointer CVDiagGetReturnFlagName(int flag);
	/**
	 * Original signature : <code>int CVLapackDense(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_lapack.h:51</i>
	 */
//	@Mangling({"_Z13CVLapackDensePvi", "?CVLapackDense@@YAHPAXH@Z"}) 
//	public static native int CVLapackDense(Pointer cvode_mem, int N);
//	/**
//	 * Original signature : <code>int CVLapackBand(void*, int, int, int)</code><br>
//	 * <i>native declaration : include\cvode\cvode_lapack.h:78</i>
//	 */
//	@Mangling({"_Z12CVLapackBandPviii", "?CVLapackBand@@YAHPAXHHH@Z"}) 
//	public static native int CVLapackBand(Pointer cvode_mem, int N, int mupper, int mlower);
//	/**
//	 * Original signature : <code>int CVSpilsSetPrecType(void*, int)</code><br>
//	 * <i>native declaration : include\cvode\cvode_spils.h:296</i>
//	 */
	@Mangling({"_Z18CVSpilsSetPrecTypePvi", "?CVSpilsSetPrecType@@YAHPAXH@Z"}) 
	public static native int CVSpilsSetPrecType(Pointer cvode_mem, int pretype);
	/**
	 * Original signature : <code>int CVSpilsSetGSType(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:297</i>
	 */
	@Mangling({"_Z16CVSpilsSetGSTypePvi", "?CVSpilsSetGSType@@YAHPAXH@Z"}) 
	public static native int CVSpilsSetGSType(Pointer cvode_mem, int gstype);
	/**
	 * Original signature : <code>int CVSpilsSetMaxl(void*, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:298</i>
	 */
	@Mangling({"_Z14CVSpilsSetMaxlPvi", "?CVSpilsSetMaxl@@YAHPAXH@Z"}) 
	public static native int CVSpilsSetMaxl(Pointer cvode_mem, int maxl);
	/**
	 * Original signature : <code>int CVSpilsSetEpsLin(void*, realtype)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:299</i>
	 */
	@Mangling({"_Z16CVSpilsSetEpsLinPvd", "?CVSpilsSetEpsLin@@YAHPAXN@Z"}) 
	public static native int CVSpilsSetEpsLin(Pointer cvode_mem, double eplifac);
	/**
	 * Original signature : <code>int CVSpilsSetPreconditioner(void*, CVSpilsPrecSetupFn, CVSpilsPrecSolveFn)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:300</i>
	 */
	@Mangling({"_Z24CVSpilsSetPreconditionerPvPFidP17_generic_N_VectorP17_generic_N_VectoriPidPvP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_VectorEPFidP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_VectorP17_generic_N_VectorddiPvP17_generic_N_VectorE", "?CVSpilsSetPreconditioner@@YAHPAXPFHNPA17_generic_N_VectorPA17_generic_N_VectorHPAHNPAXPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_Vector@EPFHNPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_VectorPA17_generic_N_VectorNNHPAXPA17_generic_N_Vector@E@Z"}) 
	public static native int CVSpilsSetPreconditioner(Pointer cvode_mem, CvodeLibrary.CVSpilsPrecSetupFn pset, CvodeLibrary.CVSpilsPrecSolveFn psolve);
	/**
	 * Original signature : <code>int CVSpilsSetJacTimesVecFn(void*, CVSpilsJacTimesVecFn)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:303</i>
	 */
	@Mangling({"_Z23CVSpilsSetJacTimesVecFnPvPFiP17_generic_N_VectorP17_generic_N_VectordP17_generic_N_VectorP17_generic_N_VectorPvP17_generic_N_VectorE", "?CVSpilsSetJacTimesVecFn@@YAHPAXPFHPA17_generic_N_VectorPA17_generic_N_VectorNPA17_generic_N_VectorPA17_generic_N_VectorPAXPA17_generic_N_Vector@E@Z"}) 
	public static native int CVSpilsSetJacTimesVecFn(Pointer cvode_mem, CvodeLibrary.CVSpilsJacTimesVecFn jtv);
	/**
	 * Original signature : <code>int CVSpilsGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:341</i><br>
	 * @deprecated use the safer methods {@link #CVSpilsGetWorkSpace(com.sun.jna.Pointer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #CVSpilsGetWorkSpace(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z19CVSpilsGetWorkSpacePvPlPl", "?CVSpilsGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	@Deprecated 
	public static native int CVSpilsGetWorkSpace(Pointer cvode_mem, IntByReference lenrwLS, IntByReference leniwLS);
	/**
	 * Original signature : <code>int CVSpilsGetWorkSpace(void*, long int*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:341</i>
	 */
	@Mangling({"_Z19CVSpilsGetWorkSpacePvPlPl", "?CVSpilsGetWorkSpace@@YAHPAXPAJPAJ@Z"}) 
	public static native int CVSpilsGetWorkSpace(Pointer cvode_mem, IntBuffer lenrwLS, IntBuffer leniwLS);
	/**
	 * Original signature : <code>int CVSpilsGetNumPrecEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:342</i><br>
	 * @deprecated use the safer methods {@link #CVSpilsGetNumPrecEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVSpilsGetNumPrecEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z22CVSpilsGetNumPrecEvalsPvPl", "?CVSpilsGetNumPrecEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVSpilsGetNumPrecEvals(Pointer cvode_mem, IntByReference npevals);
	/**
	 * Original signature : <code>int CVSpilsGetNumPrecEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:342</i>
	 */
	@Mangling({"_Z22CVSpilsGetNumPrecEvalsPvPl", "?CVSpilsGetNumPrecEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVSpilsGetNumPrecEvals(Pointer cvode_mem, IntBuffer npevals);
	/**
	 * Original signature : <code>int CVSpilsGetNumPrecSolves(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:343</i><br>
	 * @deprecated use the safer methods {@link #CVSpilsGetNumPrecSolves(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVSpilsGetNumPrecSolves(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z23CVSpilsGetNumPrecSolvesPvPl", "?CVSpilsGetNumPrecSolves@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVSpilsGetNumPrecSolves(Pointer cvode_mem, IntByReference npsolves);
	/**
	 * Original signature : <code>int CVSpilsGetNumPrecSolves(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:343</i>
	 */
	@Mangling({"_Z23CVSpilsGetNumPrecSolvesPvPl", "?CVSpilsGetNumPrecSolves@@YAHPAXPAJ@Z"}) 
	public static native int CVSpilsGetNumPrecSolves(Pointer cvode_mem, IntBuffer npsolves);
	/**
	 * Original signature : <code>int CVSpilsGetNumLinIters(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:344</i><br>
	 * @deprecated use the safer methods {@link #CVSpilsGetNumLinIters(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVSpilsGetNumLinIters(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z21CVSpilsGetNumLinItersPvPl", "?CVSpilsGetNumLinIters@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVSpilsGetNumLinIters(Pointer cvode_mem, IntByReference nliters);
	/**
	 * Original signature : <code>int CVSpilsGetNumLinIters(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:344</i>
	 */
	@Mangling({"_Z21CVSpilsGetNumLinItersPvPl", "?CVSpilsGetNumLinIters@@YAHPAXPAJ@Z"}) 
	public static native int CVSpilsGetNumLinIters(Pointer cvode_mem, IntBuffer nliters);
	/**
	 * Original signature : <code>int CVSpilsGetNumConvFails(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:345</i><br>
	 * @deprecated use the safer methods {@link #CVSpilsGetNumConvFails(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVSpilsGetNumConvFails(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z22CVSpilsGetNumConvFailsPvPl", "?CVSpilsGetNumConvFails@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVSpilsGetNumConvFails(Pointer cvode_mem, IntByReference nlcfails);
	/**
	 * Original signature : <code>int CVSpilsGetNumConvFails(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:345</i>
	 */
	@Mangling({"_Z22CVSpilsGetNumConvFailsPvPl", "?CVSpilsGetNumConvFails@@YAHPAXPAJ@Z"}) 
	public static native int CVSpilsGetNumConvFails(Pointer cvode_mem, IntBuffer nlcfails);
	/**
	 * Original signature : <code>int CVSpilsGetNumJtimesEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:346</i><br>
	 * @deprecated use the safer methods {@link #CVSpilsGetNumJtimesEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVSpilsGetNumJtimesEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z24CVSpilsGetNumJtimesEvalsPvPl", "?CVSpilsGetNumJtimesEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVSpilsGetNumJtimesEvals(Pointer cvode_mem, IntByReference njvevals);
	/**
	 * Original signature : <code>int CVSpilsGetNumJtimesEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:346</i>
	 */
	@Mangling({"_Z24CVSpilsGetNumJtimesEvalsPvPl", "?CVSpilsGetNumJtimesEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVSpilsGetNumJtimesEvals(Pointer cvode_mem, IntBuffer njvevals);
	/**
	 * Original signature : <code>int CVSpilsGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:347</i><br>
	 * @deprecated use the safer methods {@link #CVSpilsGetNumRhsEvals(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVSpilsGetNumRhsEvals(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z21CVSpilsGetNumRhsEvalsPvPl", "?CVSpilsGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	@Deprecated 
	public static native int CVSpilsGetNumRhsEvals(Pointer cvode_mem, IntByReference nfevalsLS);
	/**
	 * Original signature : <code>int CVSpilsGetNumRhsEvals(void*, long int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:347</i>
	 */
	@Mangling({"_Z21CVSpilsGetNumRhsEvalsPvPl", "?CVSpilsGetNumRhsEvals@@YAHPAXPAJ@Z"}) 
	public static native int CVSpilsGetNumRhsEvals(Pointer cvode_mem, IntBuffer nfevalsLS);
	/**
	 * Original signature : <code>int CVSpilsGetLastFlag(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:348</i><br>
	 * @deprecated use the safer methods {@link #CVSpilsGetLastFlag(com.sun.jna.Pointer, java.nio.IntBuffer)} and {@link #CVSpilsGetLastFlag(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Mangling({"_Z18CVSpilsGetLastFlagPvPi", "?CVSpilsGetLastFlag@@YAHPAXPAH@Z"}) 
	@Deprecated 
	public static native int CVSpilsGetLastFlag(Pointer cvode_mem, IntByReference flag);
	/**
	 * Original signature : <code>int CVSpilsGetLastFlag(void*, int*)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:348</i>
	 */
	@Mangling({"_Z18CVSpilsGetLastFlagPvPi", "?CVSpilsGetLastFlag@@YAHPAXPAH@Z"}) 
	public static native int CVSpilsGetLastFlag(Pointer cvode_mem, IntBuffer flag);
	/**
	 * Original signature : <code>char* CVSpilsGetReturnFlagName(int)</code><br>
	 * <i>native declaration : include\cvode\cvode_spils.h:357</i>
	 */
	@Mangling({"_Z24CVSpilsGetReturnFlagNamei", "?CVSpilsGetReturnFlagName@@YAPADH@Z"}) 
	public static native Pointer CVSpilsGetReturnFlagName(int flag);
	/**
	 * Original signature : <code>int CVSpbcg(void*, int, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_spbcgs.h:58</i>
	 */
	@Mangling({"_Z7CVSpbcgPvii", "?CVSpbcg@@YAHPAXHH@Z"}) 
	public static native int CVSpbcg(Pointer cvode_mem, int pretype, int maxl);
	/**
	 * Original signature : <code>int CVSpgmr(void*, int, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_spgmr.h:60</i>
	 */
	@Mangling({"_Z7CVSpgmrPvii", "?CVSpgmr@@YAHPAXHH@Z"}) 
	public static native int CVSpgmr(Pointer cvode_mem, int pretype, int maxl);
	/**
	 * Original signature : <code>int CVSptfqmr(void*, int, int)</code><br>
	 * <i>native declaration : include\cvode\cvode_sptfqmr.h:58</i>
	 */
	@Mangling({"_Z9CVSptfqmrPvii", "?CVSptfqmr@@YAHPAXHH@Z"}) 
	public static native int CVSptfqmr(Pointer cvode_mem, int pretype, int maxl);
	/// Undefined type
	public static interface FILE {
		
	};
}
